# Generated by Django 4.2.8 on 2024-04-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerHrMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayno', models.DateField(auto_now=True)),
                ('mmr_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('onroll', models.IntegerField(default=True)),
                ('manpower', models.IntegerField(default=True)),
                ('remarks', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'manpower_hr',
            },
        ),
        migrations.CreateModel(
            name='ManpowerplanMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('manpower', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'manpower_plan',
            },
        ),
        migrations.CreateModel(
            name='MmrMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_code', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_no', models.IntegerField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mmr_mt',
            },
        ),
        migrations.CreateModel(
            name='OtApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=100)),
                ('dayno', models.DateField()),
                ('emp_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ot_hour', models.IntegerField()),
                ('approve_status', models.IntegerField()),
                ('approve_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approve_date', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_approve_by', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_approve_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_no', models.IntegerField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ot_approval',
            },
        ),
        migrations.CreateModel(
            name='OTMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=100)),
                ('dep_code', models.CharField(max_length=100)),
                ('ot_month', models.IntegerField()),
                ('ot_daily', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ot_mt',
            },
        ),
    ]
