# Generated by Django 4.2.8 on 2024-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaTemplateMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=30)),
                ('template_desc', models.CharField(max_length=30)),
                ('buyer', models.CharField(max_length=100)),
                ('days_from', models.IntegerField()),
                ('days_to', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tna_template_mt',
            },
        ),
    ]
