# Generated by Django 4.2.8 on 2024-04-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0030_alter_commonmastertype_code'),
        ('App_db', '0002_tnatemplatemt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaTemplateDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('activity_type', models.CharField(max_length=30)),
                ('days_before', models.CharField(max_length=30)),
                ('days_after', models.CharField(max_length=30)),
                ('days_req', models.IntegerField()),
                ('Base_activity', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_group', to='IntelliSync_db.commonmaster')),
                ('activity_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_name', to='IntelliSync_db.firstlevelmaster')),
                ('tna_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='App_db.tnatemplatemt')),
            ],
            options={
                'db_table': 'tna_template_dt',
            },
        ),
    ]
