# Generated by Django 4.2.8 on 2024-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0003_tnatemplatedt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnatemplatemt',
            old_name='buyer',
            new_name='buyer_code',
        ),
        migrations.AddField(
            model_name='tnatemplatemt',
            name='buyer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
