# Generated by Django 4.2.8 on 2024-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0004_rename_buyer_tnatemplatemt_buyer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnatemplatemt',
            name='template_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tnatemplatemt',
            name='template_name',
            field=models.CharField(max_length=255),
        ),
    ]
