# Generated by Django 4.2.8 on 2024-04-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0006_alter_tnatemplatedt_base_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnatemplatedt',
            old_name='Base_activity',
            new_name='base_activity',
        ),
    ]
