# Generated by Django 4.2.8 on 2024-04-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0007_rename_base_activity_tnatemplatedt_base_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnatemplatedt',
            old_name='days_after',
            new_name='days_action',
        ),
        migrations.RemoveField(
            model_name='tnatemplatedt',
            name='days_before',
        ),
    ]
