# Generated by Django 4.2.8 on 2024-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0008_rename_days_after_tnatemplatedt_days_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnatemplatemt',
            name='booking_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
