# Generated by Django 4.2.8 on 2024-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0009_tnatemplatemt_booking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnatemplatemt',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
