# Generated by Django 4.2.8 on 2024-04-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0010_tnatemplatemt_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TnaTemplateDt',
        ),
        migrations.DeleteModel(
            name='TnaTemplateMt',
        ),
    ]
