# Generated by Django 4.2.8 on 2024-04-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0039_numberingmethod'),
        ('App_db', '0011_delete_tnatemplatedt_delete_tnatemplatemt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaTemplateMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=30)),
                ('template_name', models.CharField(max_length=255)),
                ('template_desc', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_code', models.CharField(max_length=100)),
                ('days_from', models.IntegerField()),
                ('days_to', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tna_template_mt',
            },
        ),
        migrations.CreateModel(
            name='TnaTemplateDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('activity_type', models.CharField(max_length=30)),
                ('days_action', models.CharField(max_length=30)),
                ('days_req', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_group', to='IntelliSync_db.commonmaster')),
                ('activity_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_name', to='IntelliSync_db.firstlevelmaster')),
                ('base_activity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_base_activity', to='IntelliSync_db.firstlevelmaster')),
                ('tna_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='App_db.tnatemplatemt')),
            ],
            options={
                'db_table': 'tna_template_dt',
            },
        ),
    ]
