# Generated by Django 4.2.8 on 2024-05-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0012_tnatemplatemt_tnatemplatedt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnatemplatemt',
            old_name='booking_no',
            new_name='template_no',
        ),
        migrations.AddField(
            model_name='tnatemplatedt',
            name='days_after_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tnatemplatedt',
            name='running_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
