# Generated by Django 4.2.8 on 2024-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0013_rename_booking_no_tnatemplatemt_template_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('loss_type', models.CharField(choices=[('Buyer Claim', 'Buyer Claim'), ('Discount', 'Discount'), ('Intimation', 'Intimation')], max_length=50)),
                ('loss_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=20)),
                ('buyer', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=100)),
                ('amount_fc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('debit_note_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('debit_no', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buyer_claim',
            },
        ),
    ]
