# Generated by Django 4.2.8 on 2024-06-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0015_remove_buyerclaimmodel_amount_fc'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='amount_fc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
