# Generated by Django 4.2.8 on 2024-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0019_remove_buyerclaimmodel_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
