# Generated by Django 4.2.8 on 2024-06-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0020_buyerclaimmodel_conversion_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerClaimModel',
        ),
    ]
