# Generated by Django 4.2.8 on 2024-06-03 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0022_buyerclaimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buyerclaimmodel',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
