# Generated by Django 4.2.8 on 2024-06-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0023_buyerclaimmodel_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerClaimModel',
        ),
    ]
