# Generated by Django 4.2.8 on 2024-06-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0015_alter_buyerclaimmodel_currency'),
        ('App_db', '0025_buyerclaimmodel'),
    ]

    operations = [
    ]
