# Generated by Django 4.2.8 on 2024-07-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0029_alter_tnatemplatedt_base_activity_tnaentrymt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnaentrymt',
            name='tna_template',
        ),
        migrations.DeleteModel(
            name='TnaEntryDt',
        ),
        migrations.DeleteModel(
            name='TnaEntryMt',
        ),
    ]
