# Generated by Django 4.2.8 on 2024-07-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0031_tnaentrymt_tnaentrydt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnaentrymt',
            name='tna_template',
        ),
        migrations.DeleteModel(
            name='TnaEntryDt',
        ),
        migrations.DeleteModel(
            name='TnaEntryMt',
        ),
    ]
