# Generated by Django 4.2.8 on 2024-07-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('App_db', '0033_tnaentrymt_tnaentrydt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnatemplatedt',
            name='activity_group',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_template_dt_group', to='IntelliSync_db.commonmaster'),
        ),
        migrations.AlterField(
            model_name='tnatemplatedt',
            name='activity_name',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_template_dt_name', to='IntelliSync_db.firstlevelmaster'),
        ),
        migrations.AlterField(
            model_name='tnatemplatedt',
            name='base_activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tna_template_dt_activity', to='IntelliSync_db.firstlevelmaster'),
        ),
    ]
