# Generated by Django 4.2.8 on 2024-07-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0034_alter_tnatemplatedt_activity_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyCostModel',
            new_name='EnergyCost',
        ),
    ]
