# Generated by Django 4.2.8 on 2024-07-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0035_rename_energycostmodel_energycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyCost',
        ),
    ]
