# Generated by Django 4.2.8 on 2024-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0037_energycost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverHeadMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(auto_created=True)),
                ('head_id', models.CharField(max_length=100)),
                ('unit_name', models.CharField(max_length=100)),
                ('daily_cost', models.IntegerField()),
                ('monthly_cost', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'over_head_mt',
            },
        ),
    ]
