# Generated by Django 4.2.8 on 2024-07-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0039_rename_before_after_tnaentrydt_days_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overheadmt',
            name='is_active',
        ),
    ]
