# Generated by Django 4.2.8 on 2024-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_db', '0040_remove_overheadmt_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='overheadmt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
