# Generated by Django 4.2.8 on 2024-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_db', '0002_timeearlyout_timehourday'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_code', models.IntegerField()),
                ('h_name', models.CharField(blank=True, max_length=100, null=True)),
                ('h_date', models.DateTimeField(blank=True, null=True)),
                ('h_type', models.IntegerField()),
                ('cmp_code', models.IntegerField()),
                ('tmp', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tbholi',
                'managed': False,
            },
        ),
    ]
