# Generated by Django 4.2.8 on 2024-03-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_db', '0003_holidaymaster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timehourday',
            table='tbtimeh',
        ),
    ]
