# Generated by Django 4.2.8 on 2024-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_db', '0004_alter_timehourday_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('cmp_code', models.IntegerField()),
                ('emp_code', models.IntegerField(primary_key=True, serialize=False)),
                ('month_no', models.IntegerField()),
                ('el', models.FloatField(db_column='EL')),
                ('pl', models.FloatField(db_column='PL')),
                ('cl', models.FloatField(db_column='CL')),
                ('sl', models.FloatField(db_column='SL')),
                ('co', models.FloatField(db_column='CO')),
                ('sp', models.FloatField(db_column='SP')),
                ('mt', models.FloatField(db_column='MT')),
                ('bel', models.FloatField(db_column='BEL')),
                ('bpl', models.FloatField(db_column='BPL')),
                ('bcl', models.FloatField(db_column='BCL')),
                ('bsl', models.FloatField(db_column='BSL')),
                ('bco', models.FloatField(db_column='BCO')),
                ('bsp', models.FloatField(db_column='BSP')),
                ('bmt', models.FloatField(db_column='BMT')),
                ('wd', models.FloatField()),
                ('wo', models.FloatField()),
                ('hd', models.FloatField()),
                ('ab', models.FloatField()),
                ('pd', models.FloatField()),
                ('wom', models.IntegerField()),
                ('otm', models.IntegerField()),
                ('lm', models.IntegerField()),
                ('womt', models.CharField(blank=True, max_length=7, null=True)),
                ('otmt', models.CharField(blank=True, max_length=7, null=True)),
                ('lmt', models.CharField(blank=True, max_length=7, null=True)),
                ('otrat', models.FloatField()),
                ('netm', models.IntegerField()),
                ('netmt', models.CharField(blank=True, max_length=7, null=True)),
                ('mot', models.FloatField()),
                ('maninc', models.FloatField()),
                ('ehrs', models.FloatField()),
            ],
            options={
                'db_table': 'tbmatd',
                'managed': False,
            },
        ),
    ]
