# Generated by Django 4.2.8 on 2024-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.BooleanField(default=True)),
                ('n2', models.BooleanField(default=False)),
            ],
        ),
    ]
