# Generated by Django 4.2.8 on 2024-09-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IntelliSync_db', '0046_statustrackermaster'),
        ('ERP_db', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdProcPlanMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('plan_no', models.CharField(max_length=100)),
                ('detail_type', models.CharField(max_length=100)),
                ('style_no', models.CharField(max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('u_id', models.CharField(max_length=100)),
                ('entry_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_code', models.ForeignKey(db_column='party_code', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='ERP_db.party')),
            ],
            options={
                'db_table': 'prod_proc_plan_mt',
            },
        ),
        migrations.CreateModel(
            name='ProdProcPlanDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=100)),
                ('process_no', models.IntegerField()),
                ('process_rate', models.FloatField(blank=True, default=0, null=True)),
                ('product_rate', models.FloatField(blank=True, default=0, null=True)),
                ('entry_status', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(db_column='component', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IS_erp_db.prodprocplanmt')),
                ('process', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='prod_proc_process', to='IntelliSync_db.firstlevelmaster')),
                ('product_type', models.ForeignKey(db_column='product_type', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('sub_component', models.ForeignKey(blank=True, db_column='sub_component', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.secondlevelmaster')),
            ],
            options={
                'db_table': 'prod_proc_plan_dt',
            },
        ),
    ]
