# Generated by Django 4.2.8 on 2024-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS_erp_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodprocplanmt',
            name='plan_id',
        ),
        migrations.AlterField(
            model_name='prodprocplanmt',
            name='buyer_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prodprocplanmt',
            name='entry_date',
            field=models.DateField(auto_now=True),
        ),
    ]
