# Generated by Django 4.2.8 on 2024-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS_erp_db', '0004_remove_prodprocplanmt_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodprocplanmt',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
