from .dailyAttendance import DailyAttendanceView
from .leaveApplication import LeaveView
from .odApplication import ODView
from .comoffApplication import CompOffView
from .missPunchApplication import MissPunchView
from .wfhApplication import WfhView
from .applicationListView import ApplicationListView,ApprovalOverMail,RejectOverMail
from .applicationListView import LeaveApplicationDetails
from .application_report import ApplicationReport
from .payslip_generator import PayslipGenerator
from .meetingBookingView import MeetingBookingView
from .happy_bday_mailer import HappyBdayMailer
from .team_attendance_view import TeamAttendanceView
from .generate_id_card import GenerateIdCardView