# Vendor & Buyer
from django.db import models



class Party(models.Model):
    partyid = models.BigAutoField(db_column='PartyId', primary_key=True, unique=True)
    party_code = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    party_name = models.CharField(max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    pname = models.CharField(max_length=5, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    address1 = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    address2 = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    address3 = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    address4 = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    address5 = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    city = models.CharField(max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    zip = models.CharField(max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    country = models.CharField(max_length=3, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    area_code = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    destin = models.CharField(max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    phone1 = models.CharField(max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    phone2 = models.CharField(max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    telex = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    fax = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    contact = models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    banker = models.CharField(max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    banker1 = models.CharField(max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    pay_terms = models.CharField(max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    term_cont = models.CharField(max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    issupplier = models.BooleanField(blank=True, null=True)
    isfabricsupplier = models.BooleanField(db_column='IsFabricSupplier', blank=True, null=True)
    isaccessorysupplier = models.BooleanField(db_column='IsAccessorySupplier', blank=True, null=True)
    isyarnsupplier = models.BooleanField(db_column='IsYarnSupplier', blank=True, null=True)
    isgarmentsupplier = models.BooleanField(db_column='IsGarmentSupplier', blank=True, null=True)
    isbuyer = models.BooleanField(blank=True, null=True)
    isagent = models.BooleanField(blank=True, null=True)
    isjobworker = models.BooleanField(blank=True, null=True)
    isprocessor = models.BooleanField(blank=True, null=True)
    isother = models.BooleanField(blank=True, null=True)
    islocation = models.BooleanField(db_column='isLocation', blank=True, null=True)
    cross_code = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    agent_code = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    group_name = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    cust_brok = models.CharField(max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    remarks = models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    st_no = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    cst_no = models.CharField(max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    datecreated = models.DateTimeField(blank=True, null=True)
    usercreated = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    datelastmodified = models.DateTimeField(blank=True, null=True)
    userlastmodified = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    comm_rate = models.CharField(max_length=6, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    type = models.CharField(db_column='Type', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    capacity = models.CharField(db_column='Capacity', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    mobile = models.CharField(db_column='Mobile', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    pager = models.CharField(db_column='Pager', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    email = models.CharField(db_column='Email', max_length=200, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    pay_period = models.FloatField(db_column='Pay_Period', blank=True, null=True)
    chacode = models.CharField(db_column='CHACode', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    alternateunit = models.CharField(db_column='AlternateUnit', max_length=5, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    iscontractor = models.BooleanField(db_column='isContractor', blank=True, null=True)
    regisno = models.CharField(db_column='RegisNo', max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    regisdate = models.DateTimeField(db_column='RegisDate', blank=True, null=True)
    isretailer = models.BooleanField(db_column='ISRETAILER', blank=True, null=True)
    approved = models.BooleanField(blank=True, null=True)
    ischa = models.BooleanField(db_column='isCHA', blank=True, null=True)
    isforwarder = models.BooleanField(db_column='IsForwarder', blank=True, null=True)
    ismachinerysupplier = models.BooleanField(db_column='IsMachinerySupplier', blank=True, null=True)
    speciality = models.CharField(db_column='SPECIALITY', max_length=25, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    isdistributor = models.BooleanField(db_column='Isdistributor', blank=True, null=True)
    discount = models.FloatField(blank=True, null=True)
    cst = models.FloatField(db_column='CST', blank=True, null=True)
    supplierorigin = models.CharField(db_column='SupplierOrigin', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    charate = models.FloatField(db_column='ChaRate', blank=True, null=True)
    forwarderrate = models.FloatField(db_column='ForwarderRate', blank=True, null=True)
    islab = models.IntegerField(db_column='IsLab', blank=True, null=True)
    bankactno = models.CharField(db_column='BankActNo', max_length=35, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    bank = models.CharField(db_column='Bank', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    active = models.IntegerField(db_column='Active', blank=True, null=True)
    isinternalfact = models.IntegerField(db_column='IsInternalFact', blank=True, null=True)
    exregno = models.CharField(db_column='ExRegNo', max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    busslocatcode = models.CharField(db_column='BussLocatCode', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    panno = models.CharField(db_column='PanNo', max_length=80, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    circleno = models.CharField(db_column='CircleNo', max_length=80, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    groupname = models.CharField(db_column='GroupName', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    fcurr = models.CharField(db_column='FCurr', max_length=5, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    fothch = models.FloatField(db_column='FOthCh', blank=True, null=True)
    istradingbuyer = models.IntegerField(db_column='isTradingBuyer', blank=True, null=True)
    islocalagent = models.IntegerField(db_column='isLocalAgent', blank=True, null=True)
    forwardertype = models.CharField(db_column='ForwarderType', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    attachedfile = models.CharField(db_column='AttachedFile', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    forwardermode = models.CharField(db_column='ForwarderMode', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    colorcode = models.BigIntegerField()
    seperateinventory = models.SmallIntegerField(db_column='SeperateInventory')
    tino = models.CharField(db_column='TINo', max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    tidate = models.DateTimeField(db_column='TIDate', blank=True, null=True)
    serviceno = models.CharField(db_column='ServiceNo', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    esicno = models.CharField(db_column='ESICNo', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    prodmont = models.SmallIntegerField(db_column='ProdMont')
    isfactforinvoice = models.SmallIntegerField(db_column='IsFactForInvoice', blank=True, null=True)
    compineo = models.SmallIntegerField(db_column='CompInEO')
    addmachno = models.CharField(db_column='AddMachNo', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    editmachno = models.CharField(db_column='EditMachNo', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    addbuildno = models.CharField(db_column='AddBuildNo', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    editbuildno = models.CharField(db_column='EditBuildNo', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    grouptype = models.CharField(db_column='GroupType', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    groupcompany = models.CharField(db_column='GroupCompany', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    excessshipper = models.FloatField(db_column='ExcessShipPer')
    iscourier = models.SmallIntegerField(db_column='IsCourier')
    premisis = models.CharField(max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    tinno = models.CharField(db_column='TINNo', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    vatpercentage = models.FloatField(db_column='VATPercentage')
    esiccode = models.CharField(db_column='ESICCODE', max_length=25, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    pfcode = models.CharField(db_column='PFCODE', max_length=25, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    invcurrsameasourrefcurr = models.SmallIntegerField(db_column='InvCurrSameAsOurRefCurr')
    markup = models.FloatField(db_column='MarkUp')
    packchgs = models.FloatField(db_column='PackChgs')
    mobile2 = models.CharField(db_column='Mobile2', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS')
    website = models.CharField(db_column='Website', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    limit = models.DecimalField(db_column='Limit', max_digits=18, decimal_places=2)
    distutilised = models.FloatField(db_column='DistUtilised')
    salechannel = models.CharField(db_column='SaleChannel', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    buyer1 = models.CharField(db_column='Buyer1', max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS')
    buyer1phone = models.CharField(db_column='Buyer1Phone', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    buyer1email = models.CharField(db_column='Buyer1Email', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    buyer2 = models.CharField(db_column='Buyer2', max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS')
    buyer2phone = models.CharField(db_column='Buyer2Phone', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    buyer2email = models.CharField(db_column='Buyer2Email', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    apname = models.CharField(db_column='APName', max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS')
    apphone = models.CharField(db_column='APPhone', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    apemail = models.CharField(db_column='APEmail', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    whname = models.CharField(db_column='WHName', max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS')
    whphone = models.CharField(db_column='WHPhone', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    whemail = models.CharField(db_column='WHEmail', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    licreqd = models.CharField(db_column='LicReqd', max_length=3, db_collation='SQL_Latin1_General_CP1_CI_AS')
    licname = models.CharField(db_column='LicName', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')
    profitmarginper = models.FloatField(db_column='ProfitMarginPer')
    barcodestartfrom = models.CharField(db_column='BarcodeStartFrom', max_length=6, db_collation='SQL_Latin1_General_CP1_CI_AS')
    eancode = models.CharField(db_column='EANCode', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    zonecode = models.CharField(db_column='ZoneCode', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    isindirectexp = models.SmallIntegerField(db_column='IsIndirectExp')
    servicetax = models.CharField(db_column='ServiceTax', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    pcinno = models.CharField(db_column='pCINNo', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    hideaddress = models.IntegerField(db_column='HideAddress')
    barcodemaxlength = models.IntegerField(db_column='BarcodeMaxLength')
    isapprovedfactapp = models.SmallIntegerField(db_column='IsApprovedFactApp')
    ispoimportenabled = models.SmallIntegerField(db_column='ISPOImportEnabled')
    poitemstartrowno = models.IntegerField(db_column='POItemStartRowNo')
    eancodecolumnno = models.IntegerField(db_column='EANCODEColumnNo')
    qtycolumnno = models.IntegerField(db_column='QtyColumnNo')
    bankifscode = models.CharField(db_column='BankIFSCode', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    catalogbuyer = models.SmallIntegerField(db_column='CatalogBuyer')
    isapproved = models.SmallIntegerField(db_column='IsApproved')
    partyapprby = models.CharField(db_column='PartyApprBy', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    partyappron = models.DateTimeField(db_column='PartyApprOn', blank=True, null=True)
    partyapprfrom = models.CharField(db_column='PartyApprFrom', max_length=5, db_collation='SQL_Latin1_General_CP1_CI_AS')
    statesrno = models.BigIntegerField(db_column='StateSrno')
    gstno = models.CharField(db_column='GSTNo', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    gstregstatus = models.CharField(db_column='GSTRegStatus', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS')
    gstregwefdt = models.DateTimeField(db_column='GSTRegWefDt', blank=True, null=True)
    isecommerce = models.SmallIntegerField(db_column='Isecommerce')
    isewaybillnotrequired = models.SmallIntegerField(db_column='IsEWayBillNotRequired')
    istransportewaybill = models.SmallIntegerField(db_column='IsTransportEwayBill')
    ewaytransporterid = models.CharField(db_column='EwayTransporterID', max_length=15, db_collation='SQL_Latin1_General_CP1_CI_AS')
    isinhousecontractfact = models.SmallIntegerField(db_column='IsInHouseContractFact')
    merchantexport = models.SmallIntegerField(db_column='MerchantExport')
    ismsme = models.SmallIntegerField(db_column='ISMSME')
    istcsapp = models.SmallIntegerField(db_column='IsTCSApp')
    ecommercepartyname = models.CharField(db_column='EcommercePartyName', max_length=60, db_collation='SQL_Latin1_General_CP1_CI_AS')
    ecomownportal = models.SmallIntegerField(db_column='EcomOwnPortal')
    issezparty = models.SmallIntegerField(db_column='IsSEZParty')
    compliant = models.SmallIntegerField()
    compliance = models.SmallIntegerField()
    attachedfile1 = models.CharField(db_column='AttachedFile1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    attachedfile2 = models.CharField(db_column='AttachedFile2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    attachedfile3 = models.CharField(db_column='AttachedFile3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    attachedfile4 = models.CharField(db_column='AttachedFile4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    partycurrency = models.CharField(db_column='PartyCurrency', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS')
    partyapiid = models.BigIntegerField(db_column='PartyAPIID')
    supplierapiid = models.BigIntegerField(db_column='SupplierAPIID')
    factoryapiid = models.BigIntegerField(db_column='FactoryAPIID')
    locationapiid = models.BigIntegerField(db_column='LocationAPIID')
    aliasstyleshortcode = models.CharField(db_column='AliasStyleShortCode', max_length=5, db_collation='SQL_Latin1_General_CP1_CI_AS')
    sepinvfactory = models.SmallIntegerField(db_column='SepInvFactory')

    class Meta:
        managed = False
        db_table = 'Party'
        app_label = 'ERP_db'

