from django.db import models


class Sizetype(models.Model):
    sizetypeid = models.BigAutoField(primary_key=True, unique=True, db_column='SizeTypeId')
    sizetype = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')
    s1 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s2 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s3 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s4 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s5 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s6 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s7 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s8 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s9 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s10 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s11 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s12 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s13 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s14 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s15 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s16 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s17 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s18 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s19 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s20 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s21 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s22 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s23 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s24 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s25 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s26 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s27 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s28 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s29 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s30 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    datecreated = models.DateTimeField(blank=True, null=True)
    usercreated = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    datelastmodified = models.DateTimeField(blank=True, null=True)
    userlastmodified = models.CharField(max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    numsz = models.SmallIntegerField(blank=True, null=True)
    s31 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s32 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s33 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s34 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s35 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s36 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s37 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s38 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s39 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s40 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s41 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s42 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s43 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s44 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    s45 = models.CharField(max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    active = models.SmallIntegerField(db_column='Active')
    sag1 = models.CharField(db_column='SAG1', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag2 = models.CharField(db_column='SAG2', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag3 = models.CharField(db_column='SAG3', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag4 = models.CharField(db_column='SAG4', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag5 = models.CharField(db_column='SAG5', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag6 = models.CharField(db_column='SAG6', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag7 = models.CharField(db_column='SAG7', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag8 = models.CharField(db_column='SAG8', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag9 = models.CharField(db_column='SAG9', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag10 = models.CharField(db_column='SAG10', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag11 = models.CharField(db_column='SAG11', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag12 = models.CharField(db_column='SAG12', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag13 = models.CharField(db_column='SAG13', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag14 = models.CharField(db_column='SAG14', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag15 = models.CharField(db_column='SAG15', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag16 = models.CharField(db_column='SAG16', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag17 = models.CharField(db_column='SAG17', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag18 = models.CharField(db_column='SAG18', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag19 = models.CharField(db_column='SAG19', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag20 = models.CharField(db_column='SAG20', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag21 = models.CharField(db_column='SAG21', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag22 = models.CharField(db_column='SAG22', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag23 = models.CharField(db_column='SAG23', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag24 = models.CharField(db_column='SAG24', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag25 = models.CharField(db_column='SAG25', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag26 = models.CharField(db_column='SAG26', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag27 = models.CharField(db_column='SAG27', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag28 = models.CharField(db_column='SAG28', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag29 = models.CharField(db_column='SAG29', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag30 = models.CharField(db_column='SAG30', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag31 = models.CharField(db_column='SAG31', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag32 = models.CharField(db_column='SAG32', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag33 = models.CharField(db_column='SAG33', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag34 = models.CharField(db_column='SAG34', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag35 = models.CharField(db_column='SAG35', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag36 = models.CharField(db_column='SAG36', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag37 = models.CharField(db_column='SAG37', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag38 = models.CharField(db_column='SAG38', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag39 = models.CharField(db_column='SAG39', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag40 = models.CharField(db_column='SAG40', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag41 = models.CharField(db_column='SAG41', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag42 = models.CharField(db_column='SAG42', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag43 = models.CharField(db_column='SAG43', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag44 = models.CharField(db_column='SAG44', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    sag45 = models.CharField(db_column='SAG45', max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)

    class Meta:
        managed = False
        app_label = 'ERP_db'
        db_table = 'SizeType'

