# Generated by Django 4.2.8 on 2024-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=80)),
                ('head', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'department_head',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsEmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=100, unique=True)),
                ('emp_paycode', models.CharField(max_length=100, unique=True)),
                ('emp_name', models.CharField(max_length=300)),
                ('doj', models.CharField(max_length=300)),
                ('dob', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=300)),
                ('reporting_person', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'is_employee_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_paycode', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=300, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('dep', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=300, null=True)),
                ('application_type', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_till', models.DateField(blank=True, null=True)),
                ('day_count', models.CharField(blank=True, max_length=100, null=True)),
                ('mis_in_time', models.CharField(blank=True, max_length=20, null=True)),
                ('mis_out_time', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_leave', models.CharField(blank=True, max_length=100, null=True)),
                ('address_on_leave', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_location_type', models.CharField(blank=True, max_length=300, null=True)),
                ('visit_location', models.CharField(blank=True, max_length=300, null=True)),
                ('purpose_of_visit', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='employee leave/')),
            ],
            options={
                'db_table': 'leave_application',
            },
        ),
    ]
