# Generated by Django 4.2.8 on 2024-02-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenthead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='isemployeemaster',
            options={},
        ),
    ]
