# Generated by Django 4.2.8 on 2024-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0002_alter_departmenthead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='day_part',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='working_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
