# Generated by Django 4.2.8 on 2024-02-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Payroll_db', '0003_holidaymaster'),
        ('HRMS_db', '0008_alter_leaveapplication_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isemployeemaster',
            name='reporting_person',
            field=models.ForeignKey(db_column='reporting_person', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Payroll_db.employeemaster', to_field='emp_paycode'),
        ),
    ]
