# Generated by Django 4.2.8 on 2024-02-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0010_leaveapplication_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
