# Generated by Django 4.2.8 on 2024-03-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0011_alter_leaveapplication_approved_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'managed': False},
        ),
    ]
