# Generated by Django 4.2.8 on 2024-03-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0012_alter_leaveapplication_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaveapplication',
            table='application',
        ),
    ]
