# Generated by Django 4.2.8 on 2024-04-16 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0039_numberingmethod'),
        ('Payroll_db', '0005_leavebalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0013_alter_leaveapplication_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenthead',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='isemployeemaster',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='MeetingRoomMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'meeting_room_master',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('IN', 'Internal'), ('EX', 'External')], max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booked_on', models.CharField(blank=True, max_length=100, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_attendees', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.locationmaster')),
                ('room_name', models.ForeignKey(blank=True, db_column='room_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HRMS_db.meetingroommaster')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_room_booking',
            },
        ),
        migrations.CreateModel(
            name='ManPowerRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Replacement')], max_length=20, null=True)),
                ('sub_department', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('prop_status', models.CharField(blank=True, max_length=100, null=True)),
                ('management_status', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_from', models.BigIntegerField(blank=True, null=True)),
                ('salary_to', models.BigIntegerField(blank=True, null=True)),
                ('exp_year_from', models.BigIntegerField(blank=True, null=True)),
                ('exp_year_to', models.BigIntegerField(blank=True, null=True)),
                ('special_skill_required', models.TextField(blank=True, null=True)),
                ('min_age', models.BigIntegerField(blank=True, null=True)),
                ('max_age', models.BigIntegerField(blank=True, null=True)),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_for', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_department_for', to='Payroll_db.departmentmaster')),
                ('designation_for', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_designation_for', to='Payroll_db.designationmaster')),
                ('job_location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_job_location', to='IntelliSync_db.locationmaster')),
                ('replacement_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_replacement_for', to=settings.AUTH_USER_MODEL)),
                ('report_to', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_report_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manpower_requisition',
            },
        ),
        migrations.CreateModel(
            name='ManpowerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_qualification', to='HRMS_db.manpowerrequisition')),
                ('qualification', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
            ],
            options={
                'db_table': 'manpower_requisition_degree',
            },
        ),
        migrations.CreateModel(
            name='ManpowerPreferredResidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_preffered_resident_location', to='HRMS_db.manpowerrequisition')),
                ('preferred_resident_location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.secondlevelmaster')),
            ],
            options={
                'db_table': 'manpower_requisition_location',
            },
        ),
    ]
