# Generated by Django 4.2.8 on 2024-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0014_alter_departmenthead_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='exp_year_from',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='exp_year_to',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='management_status',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='prop_status',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='salary_to',
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='age_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='exp_year_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('AHOD', 'Approved by HOD'), ('AM', 'Approved by Management')], default='P', max_length=10),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='suggested_salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='preferred_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='request_type',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Replacement'), ('A', 'Any')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='StatusTrackerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('MPR', 'Manpower Requisition')], max_length=10)),
                ('application_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('AHOD', 'Approved by HOD'), ('AM', 'Approved by Management')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'status_tracker_master',
                'unique_together': {('page', 'application_id')},
            },
        ),
    ]
