# Generated by Django 4.2.8 on 2024-04-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0015_remove_manpowerrequisition_exp_year_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manpowerrequisition',
            old_name='age_range',
            new_name='age',
        ),
    ]
