# Generated by Django 4.2.8 on 2024-04-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0016_rename_age_range_manpowerrequisition_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusTrackerMaster',
        ),
    ]
