# Generated by Django 4.2.8 on 2024-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0021_rename_age_manpowerrequisition_age_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manpowerrequisition',
            old_name='age_range',
            new_name='age',
        ),
    ]
