# Generated by Django 4.2.8 on 2024-04-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0022_rename_age_range_manpowerrequisition_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manpowerrequisition',
            old_name='age',
            new_name='age_range',
        ),
    ]
