# Generated by Django 4.2.8 on 2024-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0023_rename_age_manpowerrequisition_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroommaster',
            name='location',
        ),
        migrations.DeleteModel(
            name='MeetingRoomBooking',
        ),
        migrations.DeleteModel(
            name='MeetingRoomMaster',
        ),
    ]
