# Generated by Django 4.2.8 on 2024-04-20 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0040_statustrackermaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0024_remove_meetingroommaster_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'meeting_room_master',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('IN', 'Internal'), ('EX', 'External')], max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booked_on', models.CharField(blank=True, max_length=100, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_attendees', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.locationmaster')),
                ('room_name', models.ForeignKey(blank=True, db_column='room_name', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HRMS_db.meetingroommaster')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_room_booking',
            },
        ),
    ]
