# Generated by Django 4.2.8 on 2024-04-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0025_meetingroommaster_meetingroombooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={},
        ),
    ]
