# Generated by Django 4.2.8 on 2024-04-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0027_leaveapplication_address_leaveapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveapplication',
            unique_together=set(),
        ),
    ]
