# Generated by Django 4.2.8 on 2024-05-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0029_systemparameter_remove_meetingroombooking_booked_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemParameter',
        ),
    ]
