# Generated by Django 4.2.8 on 2024-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0030_delete_systemparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('min_limit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_limit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('parameter_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('condition', models.CharField(max_length=255)),
                ('stamp', models.DateTimeField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('perm_value', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'system_parameters',
            },
        ),
    ]
