# Generated by Django 4.2.8 on 2024-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0033_alter_systemparameter_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequisition',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
