# Generated by Django 4.2.8 on 2024-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0034_manpowerrequisition_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequisition',
            name='employee_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
