# Generated by Django 4.2.8 on 2024-06-13 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0037_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='leaveapplication',
        #     options={'managed': False},
        # ),
        # migrations.AlterField(
        #     model_name='manpowerrequisition',
        #     name='status',
        #     field=models.CharField(choices=[('P', 'Pending'), ('AHOD', 'Approved by HOD'), ('RHOD', 'Rejected by HOD'), ('AM', 'Approved by Management'), ('RM', 'Rejected by Management')], default='P', max_length=10),
        # ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
