# Generated by Django 4.2.8 on 2024-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0039_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ticket',
        #     name='response_date',
        #     field=models.DateTimeField(default=1),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='ticket',
        #     name='selection_action_about_task',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
    ]
