# Generated by Django 4.2.8 on 2024-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0040_ticket_response_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='selection_action_about_task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
