# Generated by Django 4.2.8 on 2024-07-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0042_tempcandidatelogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempCandidateLogin',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
