# Generated by Django 4.2.8 on 2024-07-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0046_ticket_approval_remark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempcandidatelogin',
            unique_together={('username', 'dob')},
        ),
    ]
