# Generated by Django 4.2.8 on 2024-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0047_alter_tempcandidatelogin_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='management_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='management_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='management_status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('NMA', 'Need Management Approval'), ('A', 'Approved'), ('D', 'Done'), ('C', 'Completed')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('S', 'Support'), ('R', 'Requirement')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
