# Generated by Django 4.2.8 on 2024-07-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0048_ticket_department_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('address_phn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('last_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_application_employment_record',
            },
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age_or_year_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('residing', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_application_family_details',
            },
        ),
        migrations.CreateModel(
            name='JobApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('father_or_husband_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('maritial_status', models.CharField(blank=True, max_length=10, null=True)),
                ('spouse', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_dependents', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.CharField(blank=True, max_length=100, null=True)),
                ('present_district', models.CharField(blank=True, max_length=100, null=True)),
                ('present_city', models.CharField(blank=True, max_length=100, null=True)),
                ('present_state', models.CharField(blank=True, max_length=100, null=True)),
                ('present_country', models.CharField(blank=True, max_length=100, null=True)),
                ('present_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('present_phone_own', models.CharField(blank=True, max_length=100, null=True)),
                ('present_phone_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_phone_own', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_phone_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('interviewed_by_us', models.BooleanField(default=False)),
                ('date_of_interview', models.DateField(blank=True, null=True)),
                ('interviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('major_achievement', models.TextField(blank=True, null=True)),
                ('career_goals', models.TextField(blank=True, null=True)),
                ('related_company_person', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('post_applied_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HRMS_db.manpowerrequisition')),
            ],
            options={
                'db_table': 'job_application',
                'unique_together': {('username', 'dob')},
            },
        ),
        migrations.CreateModel(
            name='Language_known',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('speak', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('job_application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_language_known', to='HRMS_db.jobapplicationform')),
            ],
            options={
                'db_table': 'language_known',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('main_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('special_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('job_application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_qualification', to='HRMS_db.jobapplicationform')),
            ],
            options={
                'db_table': 'job_application_qualification',
            },
        ),
        migrations.CreateModel(
            name='ReferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('job_application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_reference', to='HRMS_db.jobapplicationform')),
            ],
            options={
                'db_table': 'job_application_reference_details',
            },
        ),
        migrations.CreateModel(
            name='RelatedCompanyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('job_application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_related', to='HRMS_db.jobapplicationform')),
            ],
            options={
                'db_table': 'job_application_related_person',
            },
        ),
        migrations.DeleteModel(
            name='TempCandidateLogin',
        ),
        migrations.AddField(
            model_name='familydetails',
            name='job_application',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_family_details', to='HRMS_db.jobapplicationform'),
        ),
        migrations.AddField(
            model_name='employmentrecord',
            name='job_application',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_application_employment_record', to='HRMS_db.jobapplicationform'),
        ),
    ]
