# Generated by Django 4.2.8 on 2024-07-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0052_ticket_remove_familydetails_job_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
