# Generated by Django 4.2.8 on 2024-07-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0054_jobapplicationform_ticket_relatedcompanyperson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
