# Generated by Django 4.2.8 on 2024-07-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0056_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydetails',
            name='job_application',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicationform',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobapplicationform',
            name='post_applied_for',
        ),
        migrations.RemoveField(
            model_name='language_known',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='referencedetails',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='relatedcompanyperson',
            name='job_application',
        ),
        migrations.DeleteModel(
            name='EmploymentRecord',
        ),
        migrations.DeleteModel(
            name='FamilyDetails',
        ),
        migrations.DeleteModel(
            name='JobApplicationForm',
        ),
        migrations.DeleteModel(
            name='Language_known',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='ReferenceDetails',
        ),
        migrations.DeleteModel(
            name='RelatedCompanyPerson',
        ),
    ]
