# Generated by Django 4.2.8 on 2024-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0058_jobapplicationform_relatedcompanyperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationform',
            name='maritial_status',
            field=models.BooleanField(default=False),
        ),
    ]
