# Generated by Django 4.2.8 on 2024-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0059_alter_jobapplicationform_maritial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationform',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Other')], max_length=10, null=True),
        ),
    ]
