# Generated by Django 4.2.8 on 2024-07-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0060_alter_jobapplicationform_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationform',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('U', 'Unmarried'), ('D', 'Divorced'), ('M', 'Married')], max_length=10, null=True),
        ),
    ]
