# Generated by Django 4.2.8 on 2024-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0061_alter_jobapplicationform_maritial_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplicationform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplicationform',
            name='contact_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jobapplicationform',
            unique_together={('application_no', 'contact_no', 'dob')},
        ),
    ]
