# Generated by Django 4.2.8 on 2024-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0062_alter_jobapplicationform_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationform',
            name='contact_no',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationform',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('U', 'Unmarried'), ('D', 'Divorced')], max_length=10, null=True),
        ),
    ]
