from .manpower_planning import ManpowerPlanning
from .manpower_planning_hr import ManpowerPlanning_hr
from .mmr import Mmr
from .punching import Punchdata
from .staff_worker import Staff_worker
from .staff_worker_attr import Staff_worker_attr
from .ot_approval_add import OtApproval_view
from .ot_approval_view import OtApproval_view_all
from .ot_approval_gm import OtApproval_gm
from .ot_approval_head import OtApproval_head
from .ot_master import Ot_Master_add
from .ot_approval_unauth import OtApproval_unauth
from .daily_manpower_summ import Daily_manpower_summ
from .cutting_trans import CuttingReportView
from .finishing_trans import FinishingReportView
from .manpower_allocation import ManpowerAllocationView
from .save_data import SaveDataView
from .manpower_allocation_report import ManpowerAllocReportView