# Generated by Django 4.2.8 on 2024-07-19 11:25

import QMS_db.models.rtqm_silhouettes
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntelliSync_db', '0046_statustrackermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hindi_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('remarks', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reject', models.BooleanField(default=False)),
                ('critical', models.CharField(blank=True, choices=[('MINOR', 'MINOR'), ('MAJOR', 'MAJOR')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'defect_master',
            },
        ),
        migrations.CreateModel(
            name='ImageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='assets/media/')),
                ('image2', models.ImageField(upload_to='assets/media/')),
                ('buyer', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ObDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('parts', models.CharField(blank=True, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, max_length=1500, null=True)),
                ('type_of_machine', models.CharField(blank=True, max_length=1500, null=True)),
                ('attachments', models.CharField(blank=True, max_length=1500, null=True)),
                ('sam', models.FloatField(blank=True, null=True)),
                ('theoretical_manpower', models.FloatField(blank=True, null=True)),
                ('planned_work_station', models.IntegerField(blank=True, null=True)),
                ('target_100_pcs', models.IntegerField(blank=True, null=True)),
                ('target_60_pcs', models.IntegerField(blank=True, null=True)),
                ('seam_length', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=1500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ob_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ourref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('style_no', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('style_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Style_category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_mt',
                'unique_together': {('ourref_no', 'style_no', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProcessMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'process_master',
            },
        ),
        migrations.CreateModel(
            name='QmsPlaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ourref', models.CharField(max_length=100)),
                ('style_no', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('delvdate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('planning_no', models.CharField(blank=True, max_length=50, null=True)),
                ('planning_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('unit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'sewing_planning',
            },
        ),
        migrations.CreateModel(
            name='RtqmCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_no', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('RFT', 'PASS'), ('D', 'DEFECT'), ('R', 'REJECT')], max_length=10)),
                ('rectified', models.CharField(blank=True, choices=[('RCT', 'RECTIFIED'), ('D', 'DEFECT'), ('R', 'REJECT')], max_length=10, null=True)),
                ('defect_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('entry_date', models.CharField(max_length=11)),
                ('entry_time', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rtqm_counter',
            },
        ),
        migrations.CreateModel(
            name='RTQMSilhouettes',
            fields=[
                ('id', QMS_db.models.rtqm_silhouettes.RTQMDateID(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=100)),
                ('ourref', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('defect_operation', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rtqm_silhouettes',
            },
        ),
        migrations.CreateModel(
            name='StyleSilhouettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to='assets/media/sketches')),
                ('back_image', models.ImageField(upload_to='assets/media/sketches')),
                ('buyer', models.CharField(max_length=50)),
                ('style_no', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'style_silhouettes',
                'unique_together': {('buyer', 'style_no')},
            },
        ),
        migrations.CreateModel(
            name='SewingLineInputMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_input_qty', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.qmsplaning')),
            ],
            options={
                'db_table': 'sewing_line_input_mt',
            },
        ),
        migrations.CreateModel(
            name='SewingLineInputDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_qty', models.IntegerField(default=0)),
                ('entry_date', models.CharField(max_length=255)),
                ('entry_time', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mt_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.sewinglineinputmt')),
            ],
            options={
                'db_table': 'sewing_line_input_dt',
            },
        ),
        migrations.CreateModel(
            name='RtqmMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_no', models.CharField(max_length=30, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.qmsplaning')),
            ],
            options={
                'db_table': 'rtqm_mt',
                'unique_together': {('rtqm_no', 'planing')},
            },
        ),
        migrations.CreateModel(
            name='RtqmDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('rtqm_no', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_rtf', models.IntegerField(default=0)),
                ('total_reject', models.IntegerField(default=0)),
                ('total_defect', models.IntegerField(default=0)),
                ('total_rectified', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtqm_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt')),
            ],
            options={
                'db_table': 'rtqm_dt',
                'unique_together': {('rtqm_mt', 'size')},
            },
        ),
        migrations.CreateModel(
            name='RtqmDefectDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('rtqm_no', models.CharField(max_length=50)),
                ('ob_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('defect_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sb_x', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sb_y', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sf_x', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sf_y', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(max_length=255)),
                ('entry_time', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.defectmaster')),
                ('ob_detail', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.obdetail')),
                ('rtqm_counter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmcounter')),
                ('rtqm_dt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmdt')),
                ('rtqm_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt')),
            ],
            options={
                'db_table': 'rtqm_defect_dt',
            },
        ),
        migrations.AddField(
            model_name='rtqmcounter',
            name='rtqm_dt',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmdt'),
        ),
        migrations.AddField(
            model_name='rtqmcounter',
            name='rtqm_mt',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt'),
        ),
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('process', models.CharField(max_length=50)),
                ('orderMT_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.ordermt')),
            ],
            options={
                'db_table': 'order_process',
            },
        ),
        migrations.CreateModel(
            name='OrderDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_mt', models.ForeignKey(blank=True, db_column='order_mt', null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.ordermt')),
            ],
            options={
                'db_table': 'order_dt',
            },
        ),
        migrations.CreateModel(
            name='ObMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('style', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('line_sum', models.FloatField(blank=True, null=True)),
                ('ob_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ob_date', models.DateField(blank=True, null=True)),
                ('line_sam', models.FloatField(blank=True, null=True)),
                ('re_cutting', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('kaz_button', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('other', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_sam', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ourref', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ob_master',
            },
        ),
        migrations.AddField(
            model_name='obdetail',
            name='ob_mt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.obmaster'),
        ),
        migrations.AddField(
            model_name='defectmaster',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.processmaster'),
        ),
    ]
