# Generated by Django 4.2.8 on 2024-07-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qmsplaning',
            old_name='planning_date',
            new_name='planing_date',
        ),
        migrations.RenameField(
            model_name='qmsplaning',
            old_name='planning_no',
            new_name='planing_no',
        ),
        migrations.RenameField(
            model_name='qmsplaning',
            old_name='style_no',
            new_name='styleno',
        ),
    ]
