# Generated by Django 4.2.8 on 2024-07-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0046_statustrackermaster'),
        ('QMS_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QmsPlaning',
            new_name='SewingPlanning',
        ),
        migrations.AlterModelTable(
            name='sewingplanning',
            table='sewing_planning',
        ),
    ]
