# Generated by Django 4.2.8 on 2024-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0046_statustrackermaster'),
        ('QMS_db', '0002_rename_qmsplaning_sewingplanning_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RtqmCounter',
            new_name='SewingEndlineCounter',
        ),
        migrations.RenameModel(
            old_name='RtqmDefectDT',
            new_name='SewingEndlineDefect',
        ),
        migrations.RenameModel(
            old_name='RtqmDt',
            new_name='SewingEndlineOutputDt',
        ),
        migrations.RenameModel(
            old_name='RtqmMt',
            new_name='SewingEndlineOutputMt',
        ),
        migrations.RenameModel(
            old_name='SwingLineInputDt',
            new_name='SewingLineInputDt',
        ),
        migrations.RenameModel(
            old_name='SwingLineInputMt',
            new_name='SewingLineInputMt',
        ),
        migrations.DeleteModel(
            name='ImageMaster',
        ),
        migrations.DeleteModel(
            name='StyleSilhouettes',
        ),
    ]
