# Generated by Django 4.2.8 on 2024-07-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0003_rename_rtqmcounter_sewingendlinecounter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sewingendlinecounter',
            old_name='rtqm_dt',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='sewingendlinecounter',
            old_name='rtqm_mt',
            new_name='mt',
        ),
        migrations.RenameField(
            model_name='sewingplanning',
            old_name='planing_date',
            new_name='planning_date',
        ),
        migrations.RenameField(
            model_name='sewingplanning',
            old_name='planing_no',
            new_name='planning_no',
        ),
    ]
