# Generated by Django 4.2.8 on 2024-07-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0004_rename_rtqm_dt_sewingendlinecounter_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sewingendlinedefect',
            old_name='rtqm_counter',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='sewingendlinedefect',
            old_name='rtqm_dt',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='sewingendlinedefect',
            old_name='rtqm_mt',
            new_name='mt',
        ),
        migrations.RenameField(
            model_name='sewingendlinedefect',
            old_name='ob_detail',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='sewingendlinedefect',
            old_name='defect_name',
            new_name='operation_name',
        ),
        migrations.RenameField(
            model_name='sewinglineinputdt',
            old_name='quantity',
            new_name='input_qty',
        ),
        migrations.RemoveField(
            model_name='sewinglineinputdt',
            name='size',
        ),
        migrations.AddField(
            model_name='sewinglineinputdt',
            name='entry_date',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sewinglineinputdt',
            name='entry_time',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sewinglineinputmt',
            name='size',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sewinglineinputmt',
            name='total_input_qty',
            field=models.IntegerField(default=0),
        ),
    ]
