# Generated by Django 4.2.8 on 2024-02-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0019_alter_menumaster_parent_and_more'),
        ('HRMS_db', '0003_leaveapplication_day_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isemployeemaster',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='isemployeemaster',
            name='doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='isemployeemaster',
            name='location',
            field=models.ForeignKey(db_column='location', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.locationmaster'),
        ),
    ]
