# Generated by Django 4.2.8 on 2024-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0005_alter_isemployeemaster_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
