# Generated by Django 4.2.8 on 2024-02-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_db', '0003_holidaymaster'),
        ('HRMS_db', '0006_alter_leaveapplication_leave_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, db_column='reporting_manager', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Payroll_db.employeemaster', to_field='emp_paycode'),
        ),
    ]
