# Generated by Django 4.2.8 on 2024-02-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll_db', '0003_holidaymaster'),
        ('HRMS_db', '0009_alter_isemployeemaster_reporting_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_application_approved_by', to='Payroll_db.employeemaster'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='day_part',
            field=models.CharField(blank=True, choices=[('FD', 'Full Day'), ('HD', 'Half Day')], max_length=20, null=True),
        ),
    ]
