# Generated by Django 4.2.8 on 2024-03-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0012_alter_departmenthead_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroommaster',
            name='location',
        ),
        migrations.DeleteModel(
            name='MeetingRoomBooking',
        ),
        migrations.DeleteModel(
            name='MeetingRoomMaster',
        ),
    ]
