# Generated by Django 4.2.8 on 2024-03-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0013_remove_meetingroommaster_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={},
        ),
    ]
