# Generated by Django 4.2.8 on 2024-03-04 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0014_alter_leaveapplication_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='address_on_leave',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='leave_from',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='emp_paycode',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='approval_remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='leave_till',
            new_name='till_date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='mis_in_time',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='mis_out_time',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='purpose_of_visit',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='reason_for_leave',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='reporting_manager',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='visit_location',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='leave_application_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_application_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
