# Generated by Django 4.2.8 on 2024-03-04 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0015_rename_address_on_leave_leaveapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
