# Generated by Django 4.2.8 on 2024-03-04 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0017_remove_leaveapplication_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leave_application_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
