# Generated by Django 4.2.8 on 2024-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0019_alter_leaveapplication_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='leaveapplication',
            table='application',
        ),
    ]
