# Generated by Django 4.2.8 on 2024-03-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0020_leaveapplication_time_alter_leaveapplication_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'managed': False},
        ),
    ]
