# Generated by Django 4.2.8 on 2024-03-14 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0022_meetingroommaster_meetingroombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroombooking',
            name='meeting_host',
        ),
        migrations.AddField(
            model_name='meetingroombooking',
            name='user',
            field=models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
