# Generated by Django 4.2.8 on 2024-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0023_remove_meetingroombooking_meeting_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroommaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
