# Generated by Django 4.2.8 on 2024-03-21 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0024_meetingroommaster_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroombooking',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
