# Generated by Django 4.2.8 on 2024-03-21 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0025_alter_meetingroombooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroombooking',
            name='created_on',
        ),
        migrations.AddField(
            model_name='meetingroombooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroombooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetingroombooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
