# Generated by Django 4.2.8 on 2024-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0026_remove_meetingroombooking_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroombooking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
