# Generated by Django 4.2.8 on 2024-04-08 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRMS_db', '0027_meetingroombooking_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManPowerRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Replacement')], max_length=20, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('in_hand_salary', models.BigIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=1000, null=True)),
                ('years_of_experience', models.BigIntegerField(blank=True, null=True)),
                ('special_skill_required', models.TextField(blank=True, null=True)),
                ('preffered_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True)),
                ('preffered_resident_location', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_to', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_report_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manpower_requisition',
            },
        ),
    ]
