# Generated by Django 4.2.8 on 2024-04-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('Payroll_db', '0005_leavebalance'),
        ('HRMS_db', '0029_manpowerrequisition_department_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='in_hand_salary',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='why_replacement',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='exp_year_from',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='exp_year_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='job_location',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_job_location', to='IntelliSync_db.locationmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='preffered_age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='salary_from',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='salary_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='department_for',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_department_for', to='Payroll_db.departmentmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='replacement_employee',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_designation_for', to='Payroll_db.designationmaster'),
        ),
    ]
