# Generated by Django 4.2.8 on 2024-04-10 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payroll_db', '0005_leavebalance'),
        ('HRMS_db', '0031_alter_manpowerrequisition_replacement_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='designation_for',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_designation_for', to='Payroll_db.departmentmaster'),
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='replacement_employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_replacement_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
