# Generated by Django 4.2.8 on 2024-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('HRMS_db', '0033_alter_manpowerrequisition_designation_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='preffered_age',
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='max_age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='min_age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='preffered_resident_location',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='qualification',
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='preffered_resident_location',
            field=models.ManyToManyField(db_constraint=False, to='IntelliSync_db.secondlevelmaster'),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='qualification',
            field=models.ManyToManyField(db_constraint=False, to='IntelliSync_db.commonmaster'),
        ),
    ]
