# Generated by Django 4.2.8 on 2024-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('HRMS_db', '0034_remove_manpowerrequisition_preffered_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='preffered_resident_location',
            field=models.ManyToManyField(to='IntelliSync_db.secondlevelmaster'),
        ),
        migrations.AlterField(
            model_name='manpowerrequisition',
            name='qualification',
            field=models.ManyToManyField(to='IntelliSync_db.commonmaster'),
        ),
    ]
