# Generated by Django 4.2.8 on 2024-04-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0036_remove_manpowerrequisition_preffered_resident_location_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manpowerprefferedresidentlocation',
            table='manpower_requisition_location',
        ),
        migrations.AlterModelTable(
            name='manpowerqualification',
            table='manpower_requisition_degree',
        ),
    ]
