# Generated by Django 4.2.8 on 2024-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('HRMS_db', '0037_alter_manpowerprefferedresidentlocation_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerqualification',
            name='manpower',
        ),
        migrations.RemoveField(
            model_name='manpowerqualification',
            name='qualification',
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='preffered_resident_location',
            field=models.ManyToManyField(to='IntelliSync_db.secondlevelmaster'),
        ),
        migrations.AddField(
            model_name='manpowerrequisition',
            name='qualification',
            field=models.ManyToManyField(to='IntelliSync_db.commonmaster'),
        ),
        migrations.DeleteModel(
            name='ManpowerPrefferedResidentLocation',
        ),
        migrations.DeleteModel(
            name='ManpowerQualification',
        ),
    ]
