# Generated by Django 4.2.8 on 2024-04-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0039_manpowerqualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='preffered_resident_location',
        ),
        migrations.RemoveField(
            model_name='manpowerrequisition',
            name='qualification',
        ),
    ]
