# Generated by Django 4.2.8 on 2024-04-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0040_remove_manpowerrequisition_preffered_resident_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manpowerqualification',
            name='manpower',
        ),
        migrations.RemoveField(
            model_name='manpowerqualification',
            name='qualification',
        ),
        migrations.DeleteModel(
            name='ManpowerPrefferedResidentLocation',
        ),
        migrations.DeleteModel(
            name='ManpowerQualification',
        )
    ]
