# Generated by Django 4.2.8 on 2024-04-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMS_db', '0041_remove_manpowerqualification_manpower_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManPowerRequisition',
        ),
    ]
