# Generated by Django 4.2.8 on 2024-04-11 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('Payroll_db', '0005_leavebalance'),
        ('HRMS_db', '0042_delete_manpowerrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManPowerRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Replacement')], max_length=20, null=True)),
                ('sub_department', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('prop_status', models.CharField(blank=True, max_length=100, null=True)),
                ('management_status', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_from', models.BigIntegerField(blank=True, null=True)),
                ('salary_to', models.BigIntegerField(blank=True, null=True)),
                ('exp_year_from', models.BigIntegerField(blank=True, null=True)),
                ('exp_year_to', models.BigIntegerField(blank=True, null=True)),
                ('special_skill_required', models.TextField(blank=True, null=True)),
                ('min_age', models.BigIntegerField(blank=True, null=True)),
                ('max_age', models.BigIntegerField(blank=True, null=True)),
                ('preferred_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department_for', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_department_for', to='Payroll_db.departmentmaster')),
                ('designation_for', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_designation_for', to='Payroll_db.designationmaster')),
                ('job_location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_job_location', to='IntelliSync_db.locationmaster')),
                ('replacement_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_replacement_for', to=settings.AUTH_USER_MODEL)),
                ('report_to', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_report_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manpower_requisition',
            },
        ),
    ]
