# Generated by Django 4.2.8 on 2024-04-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('HRMS_db', '0043_manpowerrequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_qualification', to='HRMS_db.manpowerrequisition')),
                ('qualification', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
            ],
            options={
                'db_table': 'manpower_requisition_degree',
            },
        ),
        migrations.CreateModel(
            name='ManpowerPrefferedResidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requisition_preffered_resident_location', to='HRMS_db.manpowerrequisition')),
                ('preffered_resident_location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.secondlevelmaster')),
            ],
            options={
                'db_table': 'manpower_requisition_location',
            },
        ),
    ]
