# Generated by Django 4.2.8 on 2024-04-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0032_alter_commonmastertype_options_and_more'),
        ('HRMS_db', '0044_manpowerqualification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManpowerPrefferedResidentLocation',
            new_name='ManpowerPreferredResidentLocation',
        ),
        migrations.RenameField(
            model_name='manpowerpreferredresidentlocation',
            old_name='preffered_resident_location',
            new_name='preferred_resident_location',
        ),
    ]
