# Generated by Django 4.2.8 on 2023-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerplanmt',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manpowerplanmt',
            name='unit_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
