# Generated by Django 4.2.8 on 2023-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0002_manpowerplanmt_designation_manpowerplanmt_unit_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmrMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_code', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('from_date', models.CharField(max_length=100)),
                ('to_date', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mmr_mt',
            },
        ),
    ]
