# Generated by Django 4.2.8 on 2024-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0010_alter_otapproval_ot_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='otapproval',
            name='approve_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
