# Generated by Django 4.2.8 on 2024-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0015_otapproval_gm_approve_by_otapproval_gm_approve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerhrmt',
            name='dayno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
