# Generated by Django 4.2.8 on 2024-04-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0016_alter_manpowerhrmt_dayno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManpowerHrMt',
        ),
        migrations.DeleteModel(
            name='ManpowerplanMT',
        ),
        migrations.DeleteModel(
            name='MmrMT',
        ),
        migrations.DeleteModel(
            name='OtApproval',
        ),
        migrations.DeleteModel(
            name='OTMT',
        ),
    ]
