# Generated by Django 4.2.8 on 2024-04-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermt',
            name='buyer',
        ),
    ]
