# Generated by Django 4.2.8 on 2024-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0002_remove_ordermt_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermt',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
