# Generated by Django 4.2.8 on 2024-04-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0004_remove_orderdt_order_dt_remove_orderdt_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDt',
        ),
    ]
