# Generated by Django 4.2.8 on 2024-04-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0005_delete_orderdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_mt', models.ForeignKey(blank=True, db_column='order_mt', null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.ordermt')),
            ],
            options={
                'db_table': 'order_dt',
            },
        ),
    ]
