# Generated by Django 4.2.8 on 2024-04-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0006_orderdt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermt',
            name='buyer_order_no',
        ),
        migrations.RemoveField(
            model_name='ordermt',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='ordermt',
            name='style_name',
        ),
        migrations.RemoveField(
            model_name='ordermt',
            name='style_no',
        ),
    ]
