# Generated by Django 4.2.8 on 2024-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0007_alter_ordermt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermt',
            name='buyer_order_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordermt',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermt',
            name='style_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordermt',
            name='style_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
