# Generated by Django 4.2.8 on 2024-04-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0008_ordermt_buyer_order_no_ordermt_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemaster',
            name='image1',
            field=models.ImageField(upload_to='assets/media/'),
        ),
        migrations.AlterField(
            model_name='imagemaster',
            name='image2',
            field=models.ImageField(upload_to='assets/media/'),
        ),
        migrations.AlterField(
            model_name='orderprocess',
            name='orderMT_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.orderdt'),
        ),
        migrations.AlterModelTable(
            name='orderprocess',
            table='order_process',
        ),
    ]
