# Generated by Django 4.2.8 on 2024-05-23 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QMS_db', '0010_alter_orderprocess_ordermt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.CharField(blank=True, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, max_length=1500, null=True)),
                ('type_of_machine', models.CharField(blank=True, max_length=1500, null=True)),
                ('attachments', models.CharField(blank=True, max_length=1500, null=True)),
                ('sam', models.FloatField(blank=True, null=True)),
                ('theoretical_manpower', models.FloatField(blank=True, null=True)),
                ('planned_work_station', models.IntegerField(blank=True, null=True)),
                ('target_100_pcs', models.IntegerField(blank=True, null=True)),
                ('target_60_pcs', models.IntegerField(blank=True, null=True)),
                ('seam_length', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=1500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ob_detail',
            },
        ),
        migrations.CreateModel(
            name='ObMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('style', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('line_sum', models.FloatField(blank=True, null=True)),
                ('ob_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ob_date', models.DateField(blank=True, null=True)),
                ('line_sam', models.FloatField(blank=True, null=True)),
                ('re_cutting', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('kaz_button', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('other', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_sam', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ob_master',
            },
        ),
    ]
