# Generated by Django 4.2.8 on 2024-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0012_defectmaster_operationmaster_obdetail_ob_mt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectmaster',
            name='category',
            field=models.CharField(blank=True, choices=[('CR', 'CRITICAL'), ('NM', 'NORMAL')], max_length=50, null=True),
        ),
    ]
