# Generated by Django 4.2.8 on 2024-06-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('QMS_db', '0013_defectmaster_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QmsPlaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('ourref', models.CharField(max_length=100)),
                ('styleno', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('delvdate', models.DateField()),
                ('quantity', models.IntegerField()),
                ('planing_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('unit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'qms_planing',
            },
        ),
    ]
