# Generated by Django 4.2.8 on 2024-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0017_rtqmsilhouettes_stylesilhouettes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesilhouettes',
            name='back_image',
            field=models.ImageField(upload_to='assets/media/sketches'),
        ),
        migrations.AlterField(
            model_name='stylesilhouettes',
            name='front_image',
            field=models.ImageField(upload_to='assets/media/sketches'),
        ),
    ]
