# Generated by Django 4.2.8 on 2024-07-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0018_alter_stylesilhouettes_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obmaster',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='obmaster',
            name='ourref',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
