# Generated by Django 4.2.8 on 2024-07-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('QMS_db', '0020_swinglineinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingLineInputDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swing_line_input_dt',
            },
        ),
        migrations.CreateModel(
            name='SwingLineInputMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=100)),
                ('styleno', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('delvdate', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('unit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'swing_line_input_mt',
            },
        ),
        migrations.DeleteModel(
            name='SwingLineInput',
        ),
        migrations.AddField(
            model_name='swinglineinputdt',
            name='mt_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.swinglineinputmt'),
        ),
    ]
