# Generated by Django 4.2.8 on 2024-07-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0021_swinglineinputdt_swinglineinputmt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinglineinputmt',
            name='ourref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
