# Generated by Django 4.2.8 on 2024-07-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('QMS_db', '0022_swinglineinputmt_ourref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtqmMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_no', models.CharField(max_length=30, unique=True)),
                ('buyer_code', models.CharField(max_length=255)),
                ('buyer_name', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('ourref', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('total_quantity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('line', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('unit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.locationmaster')),
            ],
            options={
                'db_table': 'rtqm_mt',
                'unique_together': {('buyer_code', 'style', 'ourref', 'color')},
            },
        ),
        migrations.CreateModel(
            name='RtqmDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('rtqm_no', models.CharField(max_length=30)),
                ('size', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_quantity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_rtf', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_reject', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_defect', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_rectified', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtqm_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt')),
            ],
            options={
                'db_table': 'rtqm_dt',
                'unique_together': {('rtqm_mt', 'size')},
            },
        ),
        migrations.CreateModel(
            name='RtqmDefectDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('rtqm_no', models.CharField(max_length=30)),
                ('sb_x', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sb_y', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sf_x', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sf_y', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_date', models.CharField(max_length=30)),
                ('entry_time', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.defectmaster')),
                ('ob_detail', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.obdetail')),
                ('rtqm_dt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmdt')),
                ('rtqm_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt')),
            ],
            options={
                'db_table': 'rtqm_defect_dt',
            },
        ),
        migrations.CreateModel(
            name='RtqmCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtqm_no', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('rtqm_dt_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('RFT', 'PASS'), ('D', 'DEFECT'), ('R', 'REJECT')], max_length=5)),
                ('rectified', models.CharField(choices=[('RCT', 'RECTIFIED'), ('D', 'DEFECT'), ('R', 'REJECT')], max_length=5)),
                ('entry_date', models.CharField(max_length=11)),
                ('entry_time', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtqm_dt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmdt')),
                ('rtqm_mt', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmmt')),
            ],
            options={
                'db_table': 'rtqm_counter',
            },
        ),
    ]
