# Generated by Django 4.2.8 on 2024-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0023_rtqmmt_rtqmdt_rtqmdefectdt_rtqmcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtqmdt',
            name='total_defect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rtqmdt',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rtqmdt',
            name='total_rectified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rtqmdt',
            name='total_reject',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rtqmdt',
            name='total_rtf',
            field=models.IntegerField(default=0),
        ),
    ]
