# Generated by Django 4.2.8 on 2024-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0024_alter_rtqmdt_total_defect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtqmmt',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
