# Generated by Django 4.2.8 on 2024-07-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0026_alter_rtqmcounter_rectified_alter_rtqmcounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtqmcounter',
            name='rectified',
            field=models.CharField(blank=True, choices=[('RCT', 'RECTIFIED'), ('D', 'DEFECT'), ('R', 'REJECT')], max_length=10, null=True),
        ),
    ]
