# Generated by Django 4.2.8 on 2024-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0028_swinglineinputmt_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsplaning',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
