# Generated by Django 4.2.8 on 2024-07-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0029_qmsplaning_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtqmdefectdt',
            name='defect_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rtqmdefectdt',
            name='ob_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
