# Generated by Django 4.2.8 on 2024-07-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0030_rtqmdefectdt_defect_name_rtqmdefectdt_ob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='defect_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='entry_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='entry_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='ob_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='rtqm_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='sb_x',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='sb_y',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='sf_x',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rtqmdefectdt',
            name='sf_y',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
