# Generated by Django 4.2.8 on 2024-07-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0031_alter_rtqmdefectdt_defect_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtqmdefectdt',
            name='rtqm_counter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.rtqmcounter'),
        ),
    ]
