# Generated by Django 4.2.8 on 2024-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0032_rtqmdefectdt_rtqm_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsplaning',
            name='planing_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
