# Generated by Django 4.2.8 on 2024-07-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0033_qmsplaning_planing_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinglineinputmt',
            name='planing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.qmsplaning'),
        ),
    ]
