# Generated by Django 4.2.8 on 2024-07-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0034_swinglineinputmt_planing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='delvdate',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='line',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='ourref',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='styleno',
        ),
        migrations.RemoveField(
            model_name='swinglineinputmt',
            name='unit',
        ),
    ]
