# Generated by Django 4.2.8 on 2024-07-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0035_remove_swinglineinputmt_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtqmcounter',
            name='defect_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
