# Generated by Django 4.2.8 on 2024-07-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QMS_db', '0036_rtqmcounter_defect_counter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rtqmmt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rtqmmt',
            name='planing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='QMS_db.qmsplaning'),
        ),
        migrations.AddField(
            model_name='swinglineinputmt',
            name='total_input_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rtqmmt',
            unique_together={('rtqm_no', 'planing')},
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='buyer_code',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='line',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='ourref',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='style',
        ),
        migrations.RemoveField(
            model_name='rtqmmt',
            name='unit',
        ),
    ]
