# Generated by Django 4.2.8 on 2024-01-23 22:11

import IntelliSync_db.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'common_master',
            },
        ),
        migrations.CreateModel(
            name='CommonMasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('0', 'Common Master'), ('1', 'First Level Master'), ('2', 'Second Level Master')], default='0', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, choices=[('CT-1', 'Pattern Request Type'), ('CT-2', 'Pattern Stage Master'), ('CT-3', 'Pattern Type Master'), ('CT-4', 'Sample Type Group Master'), ('CT-5', '2nd lvl master test'), ('CT-6', 'Sample Type Master'), ('CT-7', 'Product Master'), ('CT-8', 'Process Master'), ('CT-9', 'Component Master'), ('CT-10', 'Sub Component Master'), ('CT-11', 'Sample Article Master'), ('CT-12', 'Season Master'), ('CT-13', 'Season Year Master'), ('CT-14', 'Size Master'), ('CT-15', 'Color Master'), ('CT-16', 'Defect Type Master'), ('CT-17', 'Defect Group Master'), ('CT-18', 'Defect Master'), ('CT-19', 'Month Master'), ('CT-20', 'Year Master'), ('CT-21', 'Sample Article Group Master'), ('CT-22', 'Merchant Head'), ('CT-23', 'Merchant')], default='', max_length=50, null=True, unique=True)),
                ('editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmastertype')),
            ],
            options={
                'db_table': 'common_master_type',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='CountryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=4)),
                ('name', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'country_master',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(default='', max_length=80)),
                ('name', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.companymaster')),
            ],
            options={
                'db_table': 'department_master',
            },
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(default='', max_length=80)),
                ('name', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.departmentmaster')),
            ],
            options={
                'db_table': 'designation_master',
            },
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.countrymaster')),
            ],
            options={
                'db_table': 'district_master',
            },
        ),
        migrations.CreateModel(
            name='FirstLevelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('common_master_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmastertype')),
                ('master_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flm_master_type', to='IntelliSync_db.commonmastertype')),
            ],
            options={
                'db_table': 'first_level_master',
            },
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(max_length=255)),
                ('index', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'menu_master',
                'ordering': ['module__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'permission_master',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_master',
            },
            managers=[
                ('objects', IntelliSync_db.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.menumaster')),
            ],
            options={
                'db_table': 'sub_menu_master',
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.countrymaster')),
            ],
            options={
                'db_table': 'state_master',
            },
        ),
        migrations.CreateModel(
            name='SecondLevelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('common_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmaster')),
                ('common_master_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flm_common_master_type', to='IntelliSync_db.commonmastertype')),
                ('first_level_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.firstlevelmaster')),
                ('master_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmastertype')),
            ],
            options={
                'db_table': 'second_level_master',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=100)),
                ('local_url', models.CharField(blank=True, max_length=255, null=True)),
                ('public_url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('separate_menu', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.projectmaster')),
            ],
            options={
                'db_table': 'project_master',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('permissions', models.ManyToManyField(to='IntelliSync_db.permissionmaster')),
            ],
            options={
                'db_table': 'permission_group_master',
            },
        ),
        migrations.CreateModel(
            name='PagePermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.submenumaster')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.permissionmaster')),
            ],
            options={
                'db_table': 'page_permission_master',
                'unique_together': {('page', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('local_url', models.CharField(blank=True, max_length=255, null=True)),
                ('public_url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('separate_menu', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.projectmaster')),
            ],
            options={
                'db_table': 'module_master',
            },
        ),
        migrations.AddField(
            model_name='menumaster',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.modulemaster'),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.menumaster'),
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('senior', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.departmentmaster')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.designationmaster')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.districtmaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_master',
            },
        ),
        migrations.AddField(
            model_name='districtmaster',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.statemaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.countrymaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.districtmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.statemaster'),
        ),
        migrations.AddField(
            model_name='commonmaster',
            name='master_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.commonmastertype'),
        ),
        migrations.CreateModel(
            name='UserPermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.pagepermissionmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permission_master',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='menumaster',
            unique_together={('module', 'index')},
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('address', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.companymaster')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.countrymaster')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.districtmaster')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.statemaster')),
            ],
            options={
                'db_table': 'location_master',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
