# Generated by Django 4.2.8 on 2024-01-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0005_menumaster_is_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemaster',
            name='image',
            field=models.ImageField(default='test-img.png', upload_to='modules/'),
            preserve_default=False,
        ),
    ]
