# Generated by Django 4.2.8 on 2024-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0006_modulemaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemaster',
            name='image',
            field=models.ImageField(upload_to='../modules/'),
        ),
    ]
