# Generated by Django 4.2.8 on 2024-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0007_alter_modulemaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemaster',
            name='image',
            field=models.ImageField(upload_to='modules/'),
        ),
    ]
