# Generated by Django 4.2.8 on 2024-01-31 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0008_alter_modulemaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermissionmaster',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.menumaster'),
        ),
    ]
