# Generated by Django 4.2.8 on 2024-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0009_alter_pagepermissionmaster_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaster',
            name='local_url',
        ),
        migrations.RemoveField(
            model_name='projectmaster',
            name='public_url',
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
