# Generated by Django 4.2.8 on 2024-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0010_remove_projectmaster_local_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='server_ip',
            field=models.CharField(default='', max_length=60),
        ),
    ]
