# Generated by Django 4.2.8 on 2024-02-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0012_projectmaster_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.companymaster'),
            preserve_default=False,
        ),
    ]
