# Generated by Django 4.2.8 on 2024-02-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0013_projectmaster_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonmaster',
            unique_together={('master_type', 'name')},
        ),
    ]
