# Generated by Django 4.2.8 on 2024-02-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0014_alter_commonmaster_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='firstlevelmaster',
            unique_together={('master_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='secondlevelmaster',
            unique_together={('master_type', 'name')},
        ),
    ]
