# Generated by Django 4.2.8 on 2024-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0017_companymaster_address_companymaster_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmaster',
            name='address',
            field=models.TextField(),
        ),
    ]
