# Generated by Django 4.2.8 on 2024-02-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0018_alter_locationmaster_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_set', to='IntelliSync_db.menumaster'),
        ),
        migrations.AlterUniqueTogether(
            name='firstlevelmaster',
            unique_together={('common_master', 'master_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='secondlevelmaster',
            unique_together={('common_master', 'first_level_master', 'master_type', 'name')},
        ),
    ]
