# Generated by Django 4.2.8 on 2024-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0019_alter_menumaster_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumaster',
            name='index',
            field=models.CharField(blank=True, default='999', max_length=255, null=True),
        ),
    ]
