# Generated by Django 4.2.8 on 2024-02-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0020_alter_menumaster_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menumaster',
            unique_together=set(),
        ),
    ]
