# Generated by Django 4.2.8 on 2024-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0022_alter_commonmastertype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reporting_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_top_staff',
            field=models.BooleanField(default=False),
        ),
    ]
