# Generated by Django 4.2.8 on 2024-03-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0023_user_is_reporting_manager_user_is_top_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_top_staff',
            new_name='is_super_staff',
        ),
    ]
