# Generated by Django 4.2.8 on 2024-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0026_user_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmastertype',
            name='code',
            field=models.CharField(blank=True, choices=[('CT-1', 'Pattern Request Type'), ('CT-2', 'Pattern Stage Master'), ('CT-3', 'Pattern Type Master'), ('CT-4', 'Sample Type Group Master'), ('CT-5', '2nd lvl master test'), ('CT-6', 'Sample Type Master'), ('CT-7', 'Product Master'), ('CT-8', 'Process Master'), ('CT-9', 'Component Master'), ('CT-10', 'Sub Component Master'), ('CT-11', 'Sample Article Master'), ('CT-12', 'Season Master'), ('CT-13', 'Season Year Master'), ('CT-14', 'Size Master'), ('CT-15', 'Color Master'), ('CT-16', 'Defect Type Master'), ('CT-17', 'Defect Group Master'), ('CT-18', 'Defect Master'), ('CT-19', 'Month Master'), ('CT-20', 'Year Master'), ('CT-21', 'Sample Article Group Master'), ('CT-22', 'Merchant Head'), ('CT-23', 'Merchant'), ('CT-24', 'Meeting Room Master')], default='', max_length=50, null=True, unique=True),
        ),
    ]
