# Generated by Django 4.2.8 on 2024-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0031_autoincrement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonmastertype',
            options={'ordering': ['parent__name']},
        ),
        migrations.AlterField(
            model_name='commonmastertype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
