# Generated by Django 4.2.8 on 2024-04-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0033_numberingmethod_delete_autoincrement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberingMethod',
        ),
    ]
