# Generated by Django 4.2.8 on 2024-04-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0034_delete_numberingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('prefix', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=30)),
                ('next_no', models.PositiveBigIntegerField(default=1)),
                ('day', models.BooleanField(default=False)),
                ('year', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('separator', models.CharField(default='/', max_length=1)),
            ],
            options={
                'db_table': 'numbering_method',
            },
        ),
    ]
