# Generated by Django 4.2.8 on 2024-04-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0035_numberingmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberingMethod',
        ),
    ]
