# Generated by Django 4.2.8 on 2024-04-19 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0039_numberingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTrackerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('MPR', 'Manpower Requisition')], max_length=10)),
                ('application_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('AHOD', 'Approved by HOD'), ('AM', 'Approved by Management')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_constraint='False', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_tracker_master',
                'unique_together': {('page', 'application_id')},
            },
        ),
    ]
