# Generated by Django 4.2.8 on 2024-05-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0041_alter_user_reporting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissionmaster',
            name='permission',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='IntelliSync_db.pagepermissionmaster'),
        ),
        migrations.AlterField(
            model_name='userpermissionmaster',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
