# Generated by Django 4.2.8 on 2024-05-15 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0042_alter_userpermissionmaster_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissionmaster',
            name='permission',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IntelliSync_db.pagepermissionmaster'),
        ),
        migrations.AlterField(
            model_name='userpermissionmaster',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
