# Generated by Django 4.2.8 on 2024-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0043_alter_userpermissionmaster_permission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statustrackermaster',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='statustrackermaster',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('AHOD', 'Approved by HOD'), ('RHOD', 'Rejected by HOD'), ('AM', 'Approved by Management'), ('RM', 'Rejected by Management')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='statustrackermaster',
            unique_together={('page', 'application_id', 'status')},
        ),
    ]
