# Generated by Django 4.2.8 on 2024-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusTrackerMaster',
        ),
    ]
