# Generated by Django 4.2.8 on 2024-02-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0019_alter_menumaster_parent_and_more'),
        ('Sampling_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplearticledetails',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplearticledetails',
            name='article_name',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='IntelliSync_db.firstlevelmaster'),
        ),
    ]
