# Generated by Django 4.2.8 on 2024-02-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0002_samplearticledetails_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplearticledetails',
            old_name='article_name',
            new_name='article',
        ),
    ]
