# Generated by Django 4.2.8 on 2024-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0003_rename_article_name_samplearticledetails_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebookingmt',
            name='total_qty',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplesizequantity',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='samplesizequantity',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
