# Generated by Django 4.2.8 on 2024-02-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0004_samplebookingmt_total_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebookingmt',
            name='booking_status',
            field=models.CharField(default='confirm', max_length=64),
        ),
        migrations.AddField(
            model_name='samplebookingmt',
            name='file_status',
            field=models.CharField(default='No', max_length=64),
        ),
        migrations.AddField(
            model_name='samplebookingmt',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplebookingmt',
            name='material_status',
            field=models.CharField(default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
