# Generated by Django 4.2.8 on 2024-02-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0005_samplebookingmt_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='merchant_group_name',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='merchant_name',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='sample_booking_type',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='season',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='style_no',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='cuttingentrymt',
            name='year',
        ),
        migrations.AddField(
            model_name='cuttingentrymt',
            name='booking_id',
            field=models.ForeignKey(db_column='booking_id', db_constraint=False, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cem_booking_no', to='Sampling_db.samplebookingmt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingentrymt',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingentrymt',
            name='booking_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuttingentrymt',
            name='qty',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingentrymt',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
