# Generated by Django 4.2.8 on 2024-02-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0006_remove_cuttingentrymt_booked_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingtransactiondt',
            name='booking_id',
            field=models.ForeignKey(db_column='booking_id', db_constraint=False, default='1', on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.samplebookingmt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuttingtransactiondt',
            name='booking_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
