# Generated by Django 4.2.8 on 2024-02-15 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0007_cuttingtransactiondt_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebookingmt',
            name='file_rcv_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
