# Generated by Django 4.2.8 on 2024-02-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0008_samplebookingmt_file_rcv_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingentrymt',
            name='cutting_dt',
            field=models.ForeignKey(blank=True, db_column='cutting_dt', null=True, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.cuttingtransactiondt'),
        ),
    ]
