# Generated by Django 4.2.8 on 2024-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0009_cuttingentrymt_cutting_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_status',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterModelTable(
            name='cuttingentrymt',
            table='cutting_entry_dt',
        ),
    ]
