# Generated by Django 4.2.8 on 2024-02-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0010_alter_samplebookingmt_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuttingtransactiondt',
            table='cutting_entry_mt',
        ),
    ]
