# Generated by Django 4.2.8 on 2024-02-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0011_alter_cuttingtransactiondt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingentrymt',
            name='cutting_dt',
            field=models.ForeignKey(blank=True, db_column='cutting_dt', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.cuttingtransactiondt'),
        ),
    ]
