# Generated by Django 4.2.8 on 2024-02-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0012_alter_cuttingentrymt_cutting_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchTransactionDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(default='', max_length=100)),
                ('transaction_no', models.TextField(blank=True, max_length=100, null=True)),
                ('stitch_type', models.TextField(blank=True, max_length=100, null=True)),
                ('stitch_qty', models.TextField(blank=True, max_length=100, null=True)),
                ('size_breakup', models.TextField(blank=True, max_length=100, null=True)),
                ('tailor_name', models.TextField(blank=True, max_length=100, null=True)),
                ('supervisor_name', models.TextField(blank=True, max_length=100, null=True)),
                ('checker_name', models.TextField(blank=True, max_length=100, null=True)),
                ('assign_date', models.TextField(blank=True, max_length=100, null=True)),
                ('handover_to_finish', models.TextField(blank=True, max_length=100, null=True)),
                ('expected_date', models.TextField(blank=True, max_length=100, null=True)),
                ('taken_time', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('stitch_status', models.TextField(blank=True, max_length=100, null=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.samplebookingmt')),
            ],
            options={
                'db_table': 'stitch_entry_mt',
            },
        ),
        migrations.CreateModel(
            name='StitchEntryMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(default='', max_length=100)),
                ('qty', models.PositiveBigIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sem_booking_no', to='Sampling_db.samplebookingmt')),
                ('stitch_dt', models.ForeignKey(blank=True, db_column='stitch_dt', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.stitchtransactiondt')),
            ],
            options={
                'db_table': 'stitch_entry_dt',
            },
        ),
    ]
