# Generated by Django 4.2.8 on 2024-02-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0013_stitchtransactiondt_stitchentrymt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stitchtransactiondt',
            old_name='expected_date',
            new_name='expected_time',
        ),
    ]
