# Generated by Django 4.2.8 on 2024-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0014_rename_expected_date_stitchtransactiondt_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkerstatusmt',
            name='checker_status',
            field=models.CharField(max_length=10),
        ),
    ]
