# Generated by Django 4.2.8 on 2024-02-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0016_finishtransactiondt_finishentrymt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_status',
            field=models.CharField(default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='file_status',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
