# Generated by Django 4.2.8 on 2024-02-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0018_samplebookingmt_cancelled_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplearticledetails',
            name='confirm_by_inchanrge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samplearticledetails',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
