# Generated by Django 4.2.8 on 2024-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0020_dispatchtransactiondt_dispatchentrymt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_status',
            field=models.CharField(blank=True, default='pending', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
