# Generated by Django 4.2.8 on 2024-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0021_alter_samplebookingmt_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebookingmt',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
