# Generated by Django 4.2.8 on 2024-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0022_alter_samplebookingmt_buyer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebookingmt',
            name='style_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
