# Generated by Django 4.2.8 on 2024-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0025_rename_hold_reason_dispatchtransactiondt_handover_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebookingmt',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplebookingmt',
            name='booking_type',
            field=models.CharField(choices=[('A', 'Alter'), ('F', 'Fresh'), ('R', 'Resubmission')], max_length=10),
        ),
    ]
