# Generated by Django 4.2.8 on 2024-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0026_samplebookingmt_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplebookingmt',
            old_name='cancelled_reason',
            new_name='article_hold_reason',
        ),
        migrations.RenameField(
            model_name='samplebookingmt',
            old_name='hold_reason',
            new_name='article_reject_reason',
        ),
        migrations.AddField(
            model_name='samplebookingmt',
            name='booking_cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplebookingmt',
            name='booking_hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
