# Generated by Django 4.2.8 on 2024-04-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0028_cuttingentrymt_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTransactionDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(default='', max_length=100)),
                ('transaction_no', models.TextField(blank=True, max_length=100, null=True)),
                ('other_type', models.TextField(blank=True, max_length=100, null=True)),
                ('qty', models.TextField(blank=True, max_length=100, null=True)),
                ('size_breakup', models.TextField(blank=True, max_length=100, null=True)),
                ('cutter_name', models.TextField(blank=True, max_length=100, null=True)),
                ('assign_date', models.TextField(blank=True, max_length=100, null=True)),
                ('handover_to_supervisor', models.TextField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('sample_status', models.TextField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.samplebookingmt')),
            ],
            options={
                'db_table': 'other_entry_mt',
            },
        ),
        migrations.CreateModel(
            name='OtherEntryMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(default='', max_length=100)),
                ('qty', models.PositiveBigIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='oem_booking_no', to='Sampling_db.samplebookingmt')),
                ('other_dt', models.ForeignKey(blank=True, db_column='other_dt', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.othertransactiondt')),
            ],
            options={
                'db_table': 'other_entry_dt',
            },
        ),
    ]
