# Generated by Django 4.2.8 on 2024-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0029_othertransactiondt_otherentrymt'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherentrymt',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
