# Generated by Django 4.2.8 on 2024-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0031_cuttingtransactiondt_sample_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishtransactiondt',
            name='sample_dept',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stitchtransactiondt',
            name='sample_dept',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
