# Generated by Django 4.2.8 on 2024-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0032_finishtransactiondt_sample_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchtransactiondt',
            name='sample_dept',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
