# Generated by Django 4.2.8 on 2024-04-27 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IntelliSync_db', '0040_statustrackermaster'),
        ('Sampling_db', '0033_dispatchtransactiondt_sample_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTransMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='other booking/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='other booking/')),
                ('process_type', models.CharField(max_length=30)),
                ('booking_no', models.CharField(max_length=30)),
                ('booking_type', models.CharField(choices=[('A', 'Alter'), ('F', 'Fresh'), ('R', 'Resubmission')], max_length=10)),
                ('buyer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('style_no', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateTimeField()),
                ('target_date', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_qty', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('material_status', models.CharField(default='pending', max_length=64)),
                ('booking_status', models.CharField(blank=True, default='pending', max_length=64, null=True)),
                ('file_status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('file_rcv_date', models.DateTimeField(blank=True, null=True)),
                ('article_hold_reason', models.TextField(blank=True, null=True)),
                ('article_reject_reason', models.TextField(blank=True, null=True)),
                ('booking_hold_reason', models.TextField(blank=True, null=True)),
                ('booking_cancelled_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('merchant_head', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_merchant_head', to='IntelliSync_db.commonmaster')),
                ('merchant_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_merchant_name', to='IntelliSync_db.firstlevelmaster')),
                ('product_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_product_type', to='IntelliSync_db.commonmaster')),
                ('sample_group_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_sample_type', to='IntelliSync_db.commonmaster')),
                ('sample_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_sample_type', to='IntelliSync_db.firstlevelmaster')),
                ('season', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_season', to='IntelliSync_db.commonmaster')),
                ('season_year', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='obm_year', to='IntelliSync_db.firstlevelmaster')),
            ],
            options={
                'db_table': 'other_booking_mt',
            },
        ),
        migrations.CreateModel(
            name='OtherSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sampling_db.othertransmt')),
            ],
            options={
                'db_table': 'other_size_quantity',
            },
        ),
    ]
