# Generated by Django 4.2.8 on 2024-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0034_othertransmt_othersizequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='updated_by',
        ),
    ]
