# Generated by Django 4.2.8 on 2024-06-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0035_remove_patternrequestmt_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='updated_at',
        ),
    ]
