# Generated by Django 4.2.8 on 2024-06-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0036_remove_patternrequestmt_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrequestmt',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
