# Generated by Django 4.2.8 on 2024-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0037_patternrequestmt_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrequestmt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
