# Generated by Django 4.2.8 on 2024-06-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('Sampling_db', '0038_patternrequestmt_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='expected_del_date',
        ),
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='expected_del_time',
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='merchant_head',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_request_merchant_head', to='IntelliSync_db.commonmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='no_of_pattern_develop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='target_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='merchant',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_request_merchant_name', to='IntelliSync_db.firstlevelmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='pattern_master',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='pattern_stage',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_request_pattern_stage', to='IntelliSync_db.commonmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='pattern_type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_request_pattern_type', to='IntelliSync_db.firstlevelmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_type',
            field=models.CharField(choices=[('F', 'Fresh'), ('C', 'Correction'), ('c', 'Consumption')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='style_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
