# Generated by Django 4.2.8 on 2024-06-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0039_remove_patternrequestmt_expected_del_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatternRequestMt',
        ),
    ]
