# Generated by Django 4.2.8 on 2024-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0041_patternrequestmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='target_date',
            field=models.DateTimeField(null=True),
        ),
    ]
