# Generated by Django 4.2.8 on 2024-06-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0042_remove_patternrequestmt_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='target_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
