# Generated by Django 4.2.8 on 2024-06-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0043_alter_patternrequestmt_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternrequestmt',
            name='target_date',
            field=models.DateTimeField(null=True),
        ),
    ]
