# Generated by Django 4.2.8 on 2024-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0044_alter_patternrequestmt_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_date',
            field=models.DateTimeField(null=True),
        ),
    ]
