# Generated by Django 4.2.8 on 2024-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0045_alter_patternrequestmt_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrequestmt',
            name='requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
