# Generated by Django 4.2.8 on 2024-06-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0047_finishentrysizedt'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishentrysizedt',
            name='rectify_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finishentrysizedt',
            name='rectify_date',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finishentrysizedt',
            name='rectify_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finishentrysizedt',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
