# Generated by Django 4.2.8 on 2024-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0048_finishentrysizedt_rectify_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrequestmt',
            name='pattern_cmd_date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='pattern_done',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('H', 'Hold'), ('C', 'Cancel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='pattern_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='plot_by_done',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='plot_date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='plot_done',
            field=models.CharField(blank=True, choices=[('d', 'Done'), ('h', 'Hold'), ('c', 'Cancel')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='upload_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='upload_pattern',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_request/'),
        ),
    ]
