# Generated by Django 4.2.8 on 2024-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0050_remove_othertransmt_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertransmt',
            name='process_type',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
