# Generated by Django 4.2.8 on 2024-06-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0051_othertransmt_process_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternrequestmt',
            name='upload_pattern',
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_request/'),
        ),
        migrations.AddField(
            model_name='patternrequestmt',
            name='pattern_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='pattern_request/'),
        ),
    ]
