# Generated by Django 4.2.8 on 2024-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0052_remove_patternrequestmt_upload_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternrequestmt',
            name='pattern_done',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('H', 'Hold'), ('C', 'Cancel'), ('R', 'Reject')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patternrequestmt',
            name='plot_done',
            field=models.CharField(blank=True, choices=[('d', 'Done'), ('h', 'Hold'), ('c', 'Cancel'), ('r', 'Reject')], max_length=10, null=True),
        ),
    ]
