# Generated by Django 4.2.8 on 2024-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0055_patternrequestmt_pattern_master_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternrequestmt',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
