# Generated by Django 4.2.8 on 2024-07-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('Sampling_db', '0057_raformmt_raformdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raformmt',
            name='merchant_head',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_merchant_head', to='IntelliSync_db.commonmaster'),
        ),
        migrations.AlterField(
            model_name='raformmt',
            name='merchant_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_merchant_name', to='IntelliSync_db.firstlevelmaster'),
        ),
    ]
