# Generated by Django 4.2.8 on 2024-07-05 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sampling_db', '0059_alter_raformmt_style_risk_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raformdt',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_form_dt_category_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raformdt',
            name='ra_no',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_form_dt_ra_no', to='Sampling_db.raformmt'),
        ),
    ]
