# Generated by Django 4.2.8 on 2024-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0060_alter_raformdt_created_by_alter_raformdt_ra_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othertransmt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='merchant_head',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='merchant_name',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='sample_group_type',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='season',
        ),
        migrations.RemoveField(
            model_name='othertransmt',
            name='season_year',
        ),
        migrations.DeleteModel(
            name='OtherSizeQuantity',
        ),
        migrations.DeleteModel(
            name='OtherTransMt',
        ),
    ]
