# Generated by Django 4.2.8 on 2024-07-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0062_othertransmt_othersizequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raformdt',
            name='category_index',
        ),
        migrations.AddField(
            model_name='raformdt',
            name='mt_id',
            field=models.ForeignKey(db_constraint=False, default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_form_dt_ra_no', to='Sampling_db.raformmt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raformdt',
            name='ra_no',
            field=models.CharField(max_length=30),
        ),
    ]
