# Generated by Django 4.2.8 on 2024-07-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0064_rename_buyer_raformmt_buyer_code_raformmt_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raformmt',
            old_name='buyer_code',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='raformmt',
            name='buyer_name',
        ),
    ]
