# Generated by Django 4.2.8 on 2024-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0065_rename_buyer_code_raformmt_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raformmt',
            name='ra_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
