# Generated by Django 4.2.8 on 2024-07-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntelliSync_db', '0044_alter_statustrackermaster_unique_together_and_more'),
        ('Sampling_db', '0066_alter_raformmt_ra_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raformdt',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ra_form_dt_category', to='IntelliSync_db.commonmaster'),
        ),
    ]
