# Generated by Django 4.2.8 on 2024-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sampling_db', '0067_alter_raformdt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternrequestmt',
            name='request_type',
            field=models.CharField(choices=[('F', 'Fresh'), ('CR', 'Correction'), ('CO', 'Consumption')], max_length=10),
        ),
    ]
