from django.db import models
from .employee_master import EmployeeMaster


class TimeMaster(models.Model):
    emp_code = models.ForeignKey(EmployeeMaster, on_delete=models.DO_NOTHING, db_constraint=False, related_name='time_master_emp_code', db_column='emp_code')
    month_no = models.IntegerField()
    cmp_code = models.IntegerField()
    idt1 = models.CharField(max_length=5, blank=True, null=True)
    idt2 = models.CharField(max_length=5, blank=True, null=True)
    idt3 = models.CharField(max_length=5, blank=True, null=True)
    idt4 = models.CharField(max_length=5, blank=True, null=True)
    idt5 = models.CharField(max_length=5, blank=True, null=True)
    idt6 = models.CharField(max_length=5, blank=True, null=True)
    idt7 = models.CharField(max_length=5, blank=True, null=True)
    idt8 = models.CharField(max_length=5, blank=True, null=True)
    idt9 = models.CharField(max_length=5, blank=True, null=True)
    idt10 = models.CharField(max_length=5, blank=True, null=True)
    idt11 = models.CharField(max_length=5, blank=True, null=True)
    idt12 = models.CharField(max_length=5, blank=True, null=True)
    idt13 = models.CharField(max_length=5, blank=True, null=True)
    idt14 = models.CharField(max_length=5, blank=True, null=True)
    idt15 = models.CharField(max_length=5, blank=True, null=True)
    idt16 = models.CharField(max_length=5, blank=True, null=True)
    idt17 = models.CharField(max_length=5, blank=True, null=True)
    idt18 = models.CharField(max_length=5, blank=True, null=True)
    idt19 = models.CharField(max_length=5, blank=True, null=True)
    idt20 = models.CharField(max_length=5, blank=True, null=True)
    idt21 = models.CharField(max_length=5, blank=True, null=True)
    idt22 = models.CharField(max_length=5, blank=True, null=True)
    idt23 = models.CharField(max_length=5, blank=True, null=True)
    idt24 = models.CharField(max_length=5, blank=True, null=True)
    idt25 = models.CharField(max_length=5, blank=True, null=True)
    idt26 = models.CharField(max_length=5, blank=True, null=True)
    idt27 = models.CharField(max_length=5, blank=True, null=True)
    idt28 = models.CharField(max_length=5, blank=True, null=True)
    idt29 = models.CharField(max_length=5, blank=True, null=True)
    idt30 = models.CharField(max_length=5, blank=True, null=True)
    idt31 = models.CharField(max_length=5, blank=True, null=True)
    odt1 = models.CharField(max_length=5, blank=True, null=True)
    odt2 = models.CharField(max_length=5, blank=True, null=True)
    odt3 = models.CharField(max_length=5, blank=True, null=True)
    odt4 = models.CharField(max_length=5, blank=True, null=True)
    odt5 = models.CharField(max_length=5, blank=True, null=True)
    odt6 = models.CharField(max_length=5, blank=True, null=True)
    odt7 = models.CharField(max_length=5, blank=True, null=True)
    odt8 = models.CharField(max_length=5, blank=True, null=True)
    odt9 = models.CharField(max_length=5, blank=True, null=True)
    odt10 = models.CharField(max_length=5, blank=True, null=True)
    odt11 = models.CharField(max_length=5, blank=True, null=True)
    odt12 = models.CharField(max_length=5, blank=True, null=True)
    odt13 = models.CharField(max_length=5, blank=True, null=True)
    odt14 = models.CharField(max_length=5, blank=True, null=True)
    odt15 = models.CharField(max_length=5, blank=True, null=True)
    odt16 = models.CharField(max_length=5, blank=True, null=True)
    odt17 = models.CharField(max_length=5, blank=True, null=True)
    odt18 = models.CharField(max_length=5, blank=True, null=True)
    odt19 = models.CharField(max_length=5, blank=True, null=True)
    odt20 = models.CharField(max_length=5, blank=True, null=True)
    odt21 = models.CharField(max_length=5, blank=True, null=True)
    odt22 = models.CharField(max_length=5, blank=True, null=True)
    odt23 = models.CharField(max_length=5, blank=True, null=True)
    odt24 = models.CharField(max_length=5, blank=True, null=True)
    odt25 = models.CharField(max_length=5, blank=True, null=True)
    odt26 = models.CharField(max_length=5, blank=True, null=True)
    odt27 = models.CharField(max_length=5, blank=True, null=True)
    odt28 = models.CharField(max_length=5, blank=True, null=True)
    odt29 = models.CharField(max_length=5, blank=True, null=True)
    odt30 = models.CharField(max_length=5, blank=True, null=True)
    odt31 = models.CharField(max_length=5, blank=True, null=True)
    midt1 = models.CharField(max_length=5, blank=True, null=True)
    midt2 = models.CharField(max_length=5, blank=True, null=True)
    midt3 = models.CharField(max_length=5, blank=True, null=True)
    midt4 = models.CharField(max_length=5, blank=True, null=True)
    midt5 = models.CharField(max_length=5, blank=True, null=True)
    midt6 = models.CharField(max_length=5, blank=True, null=True)
    midt7 = models.CharField(max_length=5, blank=True, null=True)
    midt8 = models.CharField(max_length=5, blank=True, null=True)
    midt9 = models.CharField(max_length=5, blank=True, null=True)
    midt10 = models.CharField(max_length=5, blank=True, null=True)
    midt11 = models.CharField(max_length=5, blank=True, null=True)
    midt12 = models.CharField(max_length=5, blank=True, null=True)
    midt13 = models.CharField(max_length=5, blank=True, null=True)
    midt14 = models.CharField(max_length=5, blank=True, null=True)
    midt15 = models.CharField(max_length=5, blank=True, null=True)
    midt16 = models.CharField(max_length=5, blank=True, null=True)
    midt17 = models.CharField(max_length=5, blank=True, null=True)
    midt18 = models.CharField(max_length=5, blank=True, null=True)
    midt19 = models.CharField(max_length=5, blank=True, null=True)
    midt20 = models.CharField(max_length=5, blank=True, null=True)
    midt21 = models.CharField(max_length=5, blank=True, null=True)
    midt22 = models.CharField(max_length=5, blank=True, null=True)
    midt23 = models.CharField(max_length=5, blank=True, null=True)
    midt24 = models.CharField(max_length=5, blank=True, null=True)
    midt25 = models.CharField(max_length=5, blank=True, null=True)
    midt26 = models.CharField(max_length=5, blank=True, null=True)
    midt27 = models.CharField(max_length=5, blank=True, null=True)
    midt28 = models.CharField(max_length=5, blank=True, null=True)
    midt29 = models.CharField(max_length=5, blank=True, null=True)
    midt30 = models.CharField(max_length=5, blank=True, null=True)
    midt31 = models.CharField(max_length=5, blank=True, null=True)
    modt1 = models.CharField(max_length=5, blank=True, null=True)
    modt2 = models.CharField(max_length=5, blank=True, null=True)
    modt3 = models.CharField(max_length=5, blank=True, null=True)
    modt4 = models.CharField(max_length=5, blank=True, null=True)
    modt5 = models.CharField(max_length=5, blank=True, null=True)
    modt6 = models.CharField(max_length=5, blank=True, null=True)
    modt7 = models.CharField(max_length=5, blank=True, null=True)
    modt8 = models.CharField(max_length=5, blank=True, null=True)
    modt9 = models.CharField(max_length=5, blank=True, null=True)
    modt10 = models.CharField(max_length=5, blank=True, null=True)
    modt11 = models.CharField(max_length=5, blank=True, null=True)
    modt12 = models.CharField(max_length=5, blank=True, null=True)
    modt13 = models.CharField(max_length=5, blank=True, null=True)
    modt14 = models.CharField(max_length=5, blank=True, null=True)
    modt15 = models.CharField(max_length=5, blank=True, null=True)
    modt16 = models.CharField(max_length=5, blank=True, null=True)
    modt17 = models.CharField(max_length=5, blank=True, null=True)
    modt18 = models.CharField(max_length=5, blank=True, null=True)
    modt19 = models.CharField(max_length=5, blank=True, null=True)
    modt20 = models.CharField(max_length=5, blank=True, null=True)
    modt21 = models.CharField(max_length=5, blank=True, null=True)
    modt22 = models.CharField(max_length=5, blank=True, null=True)
    modt23 = models.CharField(max_length=5, blank=True, null=True)
    modt24 = models.CharField(max_length=5, blank=True, null=True)
    modt25 = models.CharField(max_length=5, blank=True, null=True)
    modt26 = models.CharField(max_length=5, blank=True, null=True)
    modt27 = models.CharField(max_length=5, blank=True, null=True)
    modt28 = models.CharField(max_length=5, blank=True, null=True)
    modt29 = models.CharField(max_length=5, blank=True, null=True)
    modt30 = models.CharField(max_length=5, blank=True, null=True)
    modt31 = models.CharField(max_length=5, blank=True, null=True)
    sf1 = models.IntegerField()
    sf2 = models.IntegerField()
    sf3 = models.IntegerField()
    sf4 = models.IntegerField()
    sf5 = models.IntegerField()
    sf6 = models.IntegerField()
    sf7 = models.IntegerField()
    sf8 = models.IntegerField()
    sf9 = models.IntegerField()
    sf10 = models.IntegerField()
    sf11 = models.IntegerField()
    sf12 = models.IntegerField()
    sf13 = models.IntegerField()
    sf14 = models.IntegerField()
    sf15 = models.IntegerField()
    sf16 = models.IntegerField()
    sf17 = models.IntegerField()
    sf18 = models.IntegerField()
    sf19 = models.IntegerField()
    sf20 = models.IntegerField()
    sf21 = models.IntegerField()
    sf22 = models.IntegerField()
    sf23 = models.IntegerField()
    sf24 = models.IntegerField()
    sf25 = models.IntegerField()
    sf26 = models.IntegerField()
    sf27 = models.IntegerField()
    sf28 = models.IntegerField()
    sf29 = models.IntegerField()
    sf30 = models.IntegerField()
    sf31 = models.IntegerField()
    at1 = models.SmallIntegerField()
    at2 = models.SmallIntegerField()
    at3 = models.SmallIntegerField()
    at4 = models.SmallIntegerField()
    at5 = models.SmallIntegerField()
    at6 = models.SmallIntegerField()
    at7 = models.SmallIntegerField()
    at8 = models.SmallIntegerField()
    at9 = models.SmallIntegerField()
    at10 = models.SmallIntegerField()
    at11 = models.SmallIntegerField()
    at12 = models.SmallIntegerField()
    at13 = models.SmallIntegerField()
    at14 = models.SmallIntegerField()
    at15 = models.SmallIntegerField()
    at16 = models.SmallIntegerField()
    at17 = models.SmallIntegerField()
    at18 = models.SmallIntegerField()
    at19 = models.SmallIntegerField()
    at20 = models.SmallIntegerField()
    at21 = models.SmallIntegerField()
    at22 = models.SmallIntegerField()
    at23 = models.SmallIntegerField()
    at24 = models.SmallIntegerField()
    at25 = models.SmallIntegerField()
    at26 = models.SmallIntegerField()
    at27 = models.SmallIntegerField()
    at28 = models.SmallIntegerField()
    at29 = models.SmallIntegerField()
    at30 = models.SmallIntegerField()
    at31 = models.SmallIntegerField()
    ad1 = models.SmallIntegerField()
    ad2 = models.SmallIntegerField()
    ad3 = models.SmallIntegerField()
    ad4 = models.SmallIntegerField()
    ad5 = models.SmallIntegerField()
    ad6 = models.SmallIntegerField()
    ad7 = models.SmallIntegerField()
    ad8 = models.SmallIntegerField()
    ad9 = models.SmallIntegerField()
    ad10 = models.SmallIntegerField()
    ad11 = models.SmallIntegerField()
    ad12 = models.SmallIntegerField()
    ad13 = models.SmallIntegerField()
    ad14 = models.SmallIntegerField()
    ad15 = models.SmallIntegerField()
    ad16 = models.SmallIntegerField()
    ad17 = models.SmallIntegerField()
    ad18 = models.SmallIntegerField()
    ad19 = models.SmallIntegerField()
    ad20 = models.SmallIntegerField()
    ad21 = models.SmallIntegerField()
    ad22 = models.SmallIntegerField()
    ad23 = models.SmallIntegerField()
    ad24 = models.SmallIntegerField()
    ad25 = models.SmallIntegerField()
    ad26 = models.SmallIntegerField()
    ad27 = models.SmallIntegerField()
    ad28 = models.SmallIntegerField()
    ad29 = models.SmallIntegerField()
    ad30 = models.SmallIntegerField()
    ad31 = models.SmallIntegerField()
    lv1 = models.SmallIntegerField()
    lv2 = models.SmallIntegerField()
    lv3 = models.SmallIntegerField()
    lv4 = models.SmallIntegerField()
    lv5 = models.SmallIntegerField()
    lv6 = models.SmallIntegerField()
    lv7 = models.SmallIntegerField()
    lv8 = models.SmallIntegerField()
    lv9 = models.SmallIntegerField()
    lv10 = models.SmallIntegerField()
    lv11 = models.SmallIntegerField()
    lv12 = models.SmallIntegerField()
    lv13 = models.SmallIntegerField()
    lv14 = models.SmallIntegerField()
    lv15 = models.SmallIntegerField()
    lv16 = models.SmallIntegerField()
    lv17 = models.SmallIntegerField()
    lv18 = models.SmallIntegerField()
    lv19 = models.SmallIntegerField()
    lv20 = models.SmallIntegerField()
    lv21 = models.SmallIntegerField()
    lv22 = models.SmallIntegerField()
    lv23 = models.SmallIntegerField()
    lv24 = models.SmallIntegerField()
    lv25 = models.SmallIntegerField()
    lv26 = models.SmallIntegerField()
    lv27 = models.SmallIntegerField()
    lv28 = models.SmallIntegerField()
    lv29 = models.SmallIntegerField()
    lv30 = models.SmallIntegerField()
    lv31 = models.SmallIntegerField()
    lb1 = models.SmallIntegerField()
    lb2 = models.SmallIntegerField()
    lb3 = models.SmallIntegerField()
    lb4 = models.SmallIntegerField()
    lb5 = models.SmallIntegerField()
    lb6 = models.SmallIntegerField()
    lb7 = models.SmallIntegerField()
    lb8 = models.SmallIntegerField()
    lb9 = models.SmallIntegerField()
    lb10 = models.SmallIntegerField()
    lb11 = models.SmallIntegerField()
    lb12 = models.SmallIntegerField()
    lb13 = models.SmallIntegerField()
    lb14 = models.SmallIntegerField()
    lb15 = models.SmallIntegerField()
    lb16 = models.SmallIntegerField()
    lb17 = models.SmallIntegerField()
    lb18 = models.SmallIntegerField()
    lb19 = models.SmallIntegerField()
    lb20 = models.SmallIntegerField()
    lb21 = models.SmallIntegerField()
    lb22 = models.SmallIntegerField()
    lb23 = models.SmallIntegerField()
    lb24 = models.SmallIntegerField()
    lb25 = models.SmallIntegerField()
    lb26 = models.SmallIntegerField()
    lb27 = models.SmallIntegerField()
    lb28 = models.SmallIntegerField()
    lb29 = models.SmallIntegerField()
    lb30 = models.SmallIntegerField()
    lb31 = models.SmallIntegerField()
    wov = models.FloatField()
    wob = models.FloatField()
    won = models.FloatField()
    hwov = models.FloatField()
    hwob = models.FloatField()
    hwon = models.FloatField()

    class Meta:
        managed = False
        db_table = 'tbtime'
        app_label = 'Payroll_db'
        unique_together = (('emp_code', 'month_no'),)

