from django.db import models
from .employee_master import EmployeeMaster



class TimeEarlyOut(models.Model):
    emp_code = models.ForeignKey(EmployeeMaster,on_delete=models.DO_NOTHING,db_constraint=False, related_name='time_early_emp_code', db_column='emp_code')
    month_no = models.IntegerField()
    cmp_code = models.IntegerField()
    a1 = models.IntegerField()
    a2 = models.IntegerField()
    a3 = models.IntegerField()
    a4 = models.IntegerField()
    a5 = models.IntegerField()
    a6 = models.IntegerField()
    a7 = models.IntegerField()
    a8 = models.IntegerField()
    a9 = models.IntegerField()
    a10 = models.IntegerField()
    a11 = models.IntegerField()
    a12 = models.IntegerField()
    a13 = models.IntegerField()
    a14 = models.IntegerField()
    a15 = models.IntegerField()
    a16 = models.IntegerField()
    a17 = models.IntegerField()
    a18 = models.IntegerField()
    a19 = models.IntegerField()
    a20 = models.IntegerField()
    a21 = models.IntegerField()
    a22 = models.IntegerField()
    a23 = models.IntegerField()
    a24 = models.IntegerField()
    a25 = models.IntegerField()
    a26 = models.IntegerField()
    a27 = models.IntegerField()
    a28 = models.IntegerField()
    a29 = models.IntegerField()
    a30 = models.IntegerField()
    a31 = models.IntegerField()
    b1 = models.IntegerField()
    b2 = models.IntegerField()
    b3 = models.IntegerField()
    b4 = models.IntegerField()
    b5 = models.IntegerField()
    b6 = models.IntegerField()
    b7 = models.IntegerField()
    b8 = models.IntegerField()
    b9 = models.IntegerField()
    b10 = models.IntegerField()
    b11 = models.IntegerField()
    b12 = models.IntegerField()
    b13 = models.IntegerField()
    b14 = models.IntegerField()
    b15 = models.IntegerField()
    b16 = models.IntegerField()
    b17 = models.IntegerField()
    b18 = models.IntegerField()
    b19 = models.IntegerField()
    b20 = models.IntegerField()
    b21 = models.IntegerField()
    b22 = models.IntegerField()
    b23 = models.IntegerField()
    b24 = models.IntegerField()
    b25 = models.IntegerField()
    b26 = models.IntegerField()
    b27 = models.IntegerField()
    b28 = models.IntegerField()
    b29 = models.IntegerField()
    b30 = models.IntegerField()
    b31 = models.IntegerField()
    inc1 = models.FloatField()
    inc2 = models.FloatField()
    inc3 = models.FloatField()
    inc4 = models.FloatField()
    inc5 = models.FloatField()
    inc6 = models.FloatField()
    inc7 = models.FloatField()
    inc8 = models.FloatField()
    inc9 = models.FloatField()
    inc10 = models.FloatField()
    inc11 = models.FloatField()
    inc12 = models.FloatField()
    inc13 = models.FloatField()
    inc14 = models.FloatField()
    inc15 = models.FloatField()
    inc16 = models.FloatField()
    inc17 = models.FloatField()
    inc18 = models.FloatField()
    inc19 = models.FloatField()
    inc20 = models.FloatField()
    inc21 = models.FloatField()
    inc22 = models.FloatField()
    inc23 = models.FloatField()
    inc24 = models.FloatField()
    inc25 = models.FloatField()
    inc26 = models.FloatField()
    inc27 = models.FloatField()
    inc28 = models.FloatField()
    inc29 = models.FloatField()
    inc30 = models.FloatField()
    inc31 = models.FloatField()
    mn1 = models.IntegerField()
    mn2 = models.IntegerField()
    mn3 = models.IntegerField()
    mn4 = models.IntegerField()
    mn5 = models.IntegerField()
    mn6 = models.IntegerField()
    mn7 = models.IntegerField()
    mn8 = models.IntegerField()
    mn9 = models.IntegerField()
    mn10 = models.IntegerField()
    mn11 = models.IntegerField()
    mn12 = models.IntegerField()
    mn13 = models.IntegerField()
    mn14 = models.IntegerField()
    mn15 = models.IntegerField()
    mn16 = models.IntegerField()
    mn17 = models.IntegerField()
    mn18 = models.IntegerField()
    mn19 = models.IntegerField()
    mn20 = models.IntegerField()
    mn21 = models.IntegerField()
    mn22 = models.IntegerField()
    mn23 = models.IntegerField()
    mn24 = models.IntegerField()
    mn25 = models.IntegerField()
    mn26 = models.IntegerField()
    mn27 = models.IntegerField()
    mn28 = models.IntegerField()
    mn29 = models.IntegerField()
    mn30 = models.IntegerField()
    mn31 = models.IntegerField()
    fd1 = models.FloatField()
    fd2 = models.FloatField()
    fd3 = models.FloatField()
    fd4 = models.FloatField()
    fd5 = models.FloatField()
    fd6 = models.FloatField()
    fd7 = models.FloatField()
    fd8 = models.FloatField()
    fd9 = models.FloatField()
    fd10 = models.FloatField()
    fd11 = models.FloatField()
    fd12 = models.FloatField()
    fd13 = models.FloatField()
    fd14 = models.FloatField()
    fd15 = models.FloatField()
    fd16 = models.FloatField()
    fd17 = models.FloatField()
    fd18 = models.FloatField()
    fd19 = models.FloatField()
    fd20 = models.FloatField()
    fd21 = models.FloatField()
    fd22 = models.FloatField()
    fd23 = models.FloatField()
    fd24 = models.FloatField()
    fd25 = models.FloatField()
    fd26 = models.FloatField()
    fd27 = models.FloatField()
    fd28 = models.FloatField()
    fd29 = models.FloatField()
    fd30 = models.FloatField()
    fd31 = models.FloatField()
    tea1 = models.FloatField()
    tea2 = models.FloatField()
    tea3 = models.FloatField()
    tea4 = models.FloatField()
    tea5 = models.FloatField()
    tea6 = models.FloatField()
    tea7 = models.FloatField()
    tea8 = models.FloatField()
    tea9 = models.FloatField()
    tea10 = models.FloatField()
    tea11 = models.FloatField()
    tea12 = models.FloatField()
    tea13 = models.FloatField()
    tea14 = models.FloatField()
    tea15 = models.FloatField()
    tea16 = models.FloatField()
    tea17 = models.FloatField()
    tea18 = models.FloatField()
    tea19 = models.FloatField()
    tea20 = models.FloatField()
    tea21 = models.FloatField()
    tea22 = models.FloatField()
    tea23 = models.FloatField()
    tea24 = models.FloatField()
    tea25 = models.FloatField()
    tea26 = models.FloatField()
    tea27 = models.FloatField()
    tea28 = models.FloatField()
    tea29 = models.FloatField()
    tea30 = models.FloatField()
    tea31 = models.FloatField()
    gp1 = models.IntegerField()
    gp2 = models.IntegerField()
    gp3 = models.IntegerField()
    gp4 = models.IntegerField()
    gp5 = models.IntegerField()
    gp6 = models.IntegerField()
    gp7 = models.IntegerField()
    gp8 = models.IntegerField()
    gp9 = models.IntegerField()
    gp10 = models.IntegerField()
    gp11 = models.IntegerField()
    gp12 = models.IntegerField()
    gp13 = models.IntegerField()
    gp14 = models.IntegerField()
    gp15 = models.IntegerField()
    gp16 = models.IntegerField()
    gp17 = models.IntegerField()
    gp18 = models.IntegerField()
    gp19 = models.IntegerField()
    gp20 = models.IntegerField()
    gp21 = models.IntegerField()
    gp22 = models.IntegerField()
    gp23 = models.IntegerField()
    gp24 = models.IntegerField()
    gp25 = models.IntegerField()
    gp26 = models.IntegerField()
    gp27 = models.IntegerField()
    gp28 = models.IntegerField()
    gp29 = models.IntegerField()
    gp30 = models.IntegerField()
    gp31 = models.IntegerField()
    lot1 = models.CharField(max_length=5, blank=True, null=True)
    lot2 = models.CharField(max_length=5, blank=True, null=True)
    lot3 = models.CharField(max_length=5, blank=True, null=True)
    lot4 = models.CharField(max_length=5, blank=True, null=True)
    lot5 = models.CharField(max_length=5, blank=True, null=True)
    lot6 = models.CharField(max_length=5, blank=True, null=True)
    lot7 = models.CharField(max_length=5, blank=True, null=True)
    lot8 = models.CharField(max_length=5, blank=True, null=True)
    lot9 = models.CharField(max_length=5, blank=True, null=True)
    lot10 = models.CharField(max_length=5, blank=True, null=True)
    lot11 = models.CharField(max_length=5, blank=True, null=True)
    lot12 = models.CharField(max_length=5, blank=True, null=True)
    lot13 = models.CharField(max_length=5, blank=True, null=True)
    lot14 = models.CharField(max_length=5, blank=True, null=True)
    lot15 = models.CharField(max_length=5, blank=True, null=True)
    lot16 = models.CharField(max_length=5, blank=True, null=True)
    lot17 = models.CharField(max_length=5, blank=True, null=True)
    lot18 = models.CharField(max_length=5, blank=True, null=True)
    lot19 = models.CharField(max_length=5, blank=True, null=True)
    lot20 = models.CharField(max_length=5, blank=True, null=True)
    lot21 = models.CharField(max_length=5, blank=True, null=True)
    lot22 = models.CharField(max_length=5, blank=True, null=True)
    lot23 = models.CharField(max_length=5, blank=True, null=True)
    lot24 = models.CharField(max_length=5, blank=True, null=True)
    lot25 = models.CharField(max_length=5, blank=True, null=True)
    lot26 = models.CharField(max_length=5, blank=True, null=True)
    lot27 = models.CharField(max_length=5, blank=True, null=True)
    lot28 = models.CharField(max_length=5, blank=True, null=True)
    lot29 = models.CharField(max_length=5, blank=True, null=True)
    lot30 = models.CharField(max_length=5, blank=True, null=True)
    lot31 = models.CharField(max_length=5, blank=True, null=True)
    lin1 = models.CharField(max_length=5, blank=True, null=True)
    lin2 = models.CharField(max_length=5, blank=True, null=True)
    lin3 = models.CharField(max_length=5, blank=True, null=True)
    lin4 = models.CharField(max_length=5, blank=True, null=True)
    lin5 = models.CharField(max_length=5, blank=True, null=True)
    lin6 = models.CharField(max_length=5, blank=True, null=True)
    lin7 = models.CharField(max_length=5, blank=True, null=True)
    lin8 = models.CharField(max_length=5, blank=True, null=True)
    lin9 = models.CharField(max_length=5, blank=True, null=True)
    lin10 = models.CharField(max_length=5, blank=True, null=True)
    lin11 = models.CharField(max_length=5, blank=True, null=True)
    lin12 = models.CharField(max_length=5, blank=True, null=True)
    lin13 = models.CharField(max_length=5, blank=True, null=True)
    lin14 = models.CharField(max_length=5, blank=True, null=True)
    lin15 = models.CharField(max_length=5, blank=True, null=True)
    lin16 = models.CharField(max_length=5, blank=True, null=True)
    lin17 = models.CharField(max_length=5, blank=True, null=True)
    lin18 = models.CharField(max_length=5, blank=True, null=True)
    lin19 = models.CharField(max_length=5, blank=True, null=True)
    lin20 = models.CharField(max_length=5, blank=True, null=True)
    lin21 = models.CharField(max_length=5, blank=True, null=True)
    lin22 = models.CharField(max_length=5, blank=True, null=True)
    lin23 = models.CharField(max_length=5, blank=True, null=True)
    lin24 = models.CharField(max_length=5, blank=True, null=True)
    lin25 = models.CharField(max_length=5, blank=True, null=True)
    lin26 = models.CharField(max_length=5, blank=True, null=True)
    lin27 = models.CharField(max_length=5, blank=True, null=True)
    lin28 = models.CharField(max_length=5, blank=True, null=True)
    lin29 = models.CharField(max_length=5, blank=True, null=True)
    lin30 = models.CharField(max_length=5, blank=True, null=True)
    lin31 = models.CharField(max_length=5, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbtimetmp'
        unique_together = (('emp_code', 'month_no'),)
