# Generated by Django 4.2.8 on 2023-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0003_mmrmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerHrMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('manpower', models.IntegerField()),
                ('remarks', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manpower_hr',
            },
        ),
    ]
