# Generated by Django 4.2.8 on 2023-12-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0004_manpowerhrmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerhrmt',
            name='onroll',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='mmrmt',
            name='auto_no',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='manpowerhrmt',
            name='manpower',
            field=models.IntegerField(default=True),
        ),
    ]
