# Generated by Django 4.2.8 on 2024-01-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0005_manpowerhrmt_onroll_mmrmt_auto_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=100)),
                ('dayno', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ot_hour', models.CharField(max_length=100)),
                ('approve_by', models.CharField(max_length=100)),
                ('approve_date', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_no', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'ot_approval',
            },
        ),
    ]
