# Generated by Django 4.2.8 on 2024-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0012_otmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerhrmt',
            name='dayno',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
