# Generated by Django 4.2.8 on 2024-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0013_manpowerhrmt_dayno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerhrmt',
            name='dayno',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mmrmt',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mmrmt',
            name='to_date',
            field=models.DateField(),
        ),
    ]
