# Generated by Django 4.2.8 on 2024-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miscellaneous', '0014_alter_manpowerhrmt_dayno_alter_mmrmt_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otapproval',
            name='gm_approve_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otapproval',
            name='gm_approve_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
