# Generated by Django 4.2.8 on 2024-03-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payroll_db', '0005_leavebalance'),
        ('IntelliSync_db', '0030_alter_commonmastertype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaActivityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=30)),
                ('activity_mapping', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_group', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_group', to='IntelliSync_db.commonmaster')),
                ('activity_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_id', to='IntelliSync_db.firstlevelmaster')),
                ('activity_name', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_name', to='IntelliSync_db.firstlevelmaster')),
                ('activity_responsible', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tna_activity_responsible', to='Payroll_db.departmentmaster')),
            ],
            options={
                'db_table': 'tna_activity_master',
            },
        ),
    ]
