# Generated by Django 4.2.8 on 2024-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TnAMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnaTemplateMt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=30)),
                ('template_name', models.CharField(max_length=30)),
                ('template_desc', models.CharField(max_length=30)),
                ('buyer_code', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=100)),
                ('days_from', models.IntegerField(max_length=2)),
                ('days_to', models.IntegerField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tna_template_mt',
            },
        ),
    ]
