# Generated by Django 4.2.8 on 2024-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TnAMaster', '0002_tnatemplatemt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnaactivitymaster',
            name='activity_group',
        ),
        migrations.RemoveField(
            model_name='tnaactivitymaster',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='tnaactivitymaster',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='tnaactivitymaster',
            name='activity_responsible',
        ),
        migrations.DeleteModel(
            name='TnaTemplateMt',
        ),
        migrations.DeleteModel(
            name='TnaActivityMaster',
        ),
    ]
