from .leaveApplication import LeaveApplication
from .is_employee_master import IsEmployeeMaster
from .meeting_room_master import MeetingRoomMaster
from .meeting_room_booking import MeetingRoomBooking
from .manpower_requisition import ManPowerRequisition ,ManpowerQualification,ManpowerPreferredResidentLocation
from .system_parameters import SystemParameter
from .ticket import Ticket
from .job_application import JobApplicationForm,Language_known,Qualification,EmploymentRecord,FamilyDetails,ReferenceDetails,RelatedCompanyPerson
